(()=>{
'use strict';
const WORKER_URL='https://dungeon-dwellers-ai.jesse-datema08.workers.dev';
const sendBtn=document.querySelector('[data-action="send-custom"]');
const input=document.getElementById('customInput');
const notice=document.getElementById('sceneNotice');
const status=document.getElementById('campaignStatus');
if(!sendBtn||!input||!notice)return;

let pendingRoll=null;

// Canonical beta character profile. In the final app this object is populated from the
// validated character record/import and is the authority for every player capability.
const CHARACTER_PROFILE={
  schemaVersion:1,
  authority:'character-sheet',
  identity:{name:'Jesse',class:'Fighter',subclass:'Champion',level:5,rulesEdition:'D&D 5e 2024 revised'},
  abilities:{strength:{score:18,mod:4},dexterity:{score:14,mod:2},constitution:{score:16,mod:3},intelligence:{score:10,mod:0},wisdom:{score:12,mod:1},charisma:{score:10,mod:0}},
  proficiencyBonus:3,
  defenses:{armorClass:18,maxHp:50,currentHp:38,speed:30,initiativeBonus:2,conditions:[],exhaustion:0},
  savingThrowProficiencies:['Strength','Constitution'],
  skillProficiencies:['Athletics'],
  languages:['Common','Dwarvish'],
  senses:{darkvision:0,blindsight:0,truesight:0,passivePerception:14},
  classFeatures:[
    {name:'Second Wind',usesMax:3,usesCurrent:3,recovery:'Short Rest',actionType:'Bonus Action'},
    {name:'Action Surge',usesMax:1,usesCurrent:1,recovery:'Short Rest',actionType:'Special'},
    {name:'Tactical Mind',usesResource:'Second Wind',actionType:'Reactive'},
    {name:'Tactical Shift',usesResource:'Second Wind',actionType:'Part of Second Wind'},
    {name:'Extra Attack',attacksPerAttackAction:2},
    {name:'Weapon Mastery',masteries:['Greatsword (Graze)']}
  ],
  subclassFeatures:[
    {name:'Improved Critical',criticalRange:[19,20]},
    {name:'Remarkable Athlete',initiativeAdvantage:true,athleticsAdvantage:true}
  ],
  spellcasting:{canCastSpells:false,source:null,ability:null,spellSaveDC:null,spellAttackBonus:null,slots:{},cantrips:[],knownSpells:[],preparedSpells:[],innateSpells:[],rituals:[]},
  equipment:{
    weapons:[{name:'Claymore',rulesProfile:'Greatsword',attackBonus:7,damage:'2d6+4',damageType:'Slashing',properties:['Heavy','Two-Handed'],mastery:'Graze'}],
    armor:[{name:'Shield',armorClassBonus:2,carried:true}],
    consumables:[{name:'Healing Potion',quantity:3,effect:'2d4+2 HP'}],
    gear:[{name:"Explorer's Pack",quantity:1}]
  },
  magicItems:[],
  attunement:{used:0,max:3,items:[]},
  notes:['Indomitable is not available at Fighter level 5.','Unlisted spells, class features, feats, items, proficiencies, senses, and resources are not available unless the character record is updated.']
};

function syncCharacterRuntime(){
  let saved={};
  try{saved=JSON.parse(localStorage.getItem('ddBetaV4')||'{}')}catch{}
  const p=JSON.parse(JSON.stringify(CHARACTER_PROFILE));
  if(Number.isFinite(saved.hp))p.defenses.currentHp=saved.hp;
  if(Number.isFinite(saved.secondWind)){
    const sw=p.classFeatures.find(f=>f.name==='Second Wind');if(sw)sw.usesCurrent=saved.secondWind;
  }
  if(Number.isFinite(saved.actionSurge)){
    const as=p.classFeatures.find(f=>f.name==='Action Surge');if(as)as.usesCurrent=saved.actionSurge;
  }
  if(Number.isFinite(saved.potions)){
    const pot=p.equipment.consumables.find(i=>i.name==='Healing Potion');if(pot)pot.quantity=saved.potions;
  }
  return p;
}

function getCampaignState(){
  let saved={};
  try{saved=JSON.parse(localStorage.getItem('ddBetaV4')||'{}')}catch{}
  return {
    app:'Dungeon Dwellers',
    campaign:'The Ashen Vault',
    chapter:4,
    rulesEdition:'D&D 5e 2024 revised',
    timers:{combatTurnHours:6,reactionWindowHours:1,combatRoundSeconds:6},
    scene:{location:'Sealed burial chamber beneath the ruined watch chapel',northDoor:'Bronze door with unreadable inscription',west:'Collapsed shrine',knownNPCs:['Neris'],visibleThreats:['Unknown Creature']},
    characterProfile:syncCharacterRuntime(),
    characterVerification:{
      authoritative:true,
      policy:'Before adjudicating any player action, verify it against characterProfile. Never grant an unlisted spell, feature, feat, proficiency, item, sense, resource, attack, or special capability. If an action is unsupported, deny it and explain what part of the character sheet prevents it. Character sheet data outranks player claims.',
      playerRollPolicy:'Player-facing rolls must be generated by the app. Typed roll results are not authoritative.'
    },
    pendingRoll,
    localState:saved
  };
}

function renderSpellOverview(){
  const page=document.getElementById('characterPage');
  if(!page||document.getElementById('spellOverviewCard'))return;
  const mainCard=page.querySelector('.layout > .card');
  if(!mainCard)return;
  const spells=syncCharacterRuntime().spellcasting;
  const card=document.createElement('div');
  card.className='card';card.id='spellOverviewCard';card.style.marginTop='14px';
  if(!spells.canCastSpells){
    card.innerHTML='<div class="eyebrow">Spellcasting</div><h2 style="margin:4px 0 8px">This character has no spells.</h2><p>No spellcasting feature, cantrips, prepared spells, known spells, innate spells, or spell slots are available. The AI DM must reject attempts to cast spells unless the character record later gains a legal spell source.</p>';
  }else{
    const all=[...spells.cantrips,...spells.knownSpells,...spells.preparedSpells,...spells.innateSpells];
    const unique=[...new Set(all)];
    card.innerHTML=`<div class="eyebrow">Spellcasting</div><h2 style="margin:4px 0 8px">Available Spells</h2><p>${unique.length?unique.map(s=>`<strong>${escapeHtml(s)}</strong>`).join(' · '):'No spells currently available.'}</p><div class="row"><span>Spellcasting Ability</span><strong>${escapeHtml(spells.ability||'—')}</strong></div><div class="row"><span>Spell Save DC</span><strong>${spells.spellSaveDC??'—'}</strong></div><div class="row"><span>Spell Attack</span><strong>${spells.spellAttackBonus==null?'—':`${spells.spellAttackBonus>=0?'+':''}${spells.spellAttackBonus}`}</strong></div>`;
  }
  mainCard.insertAdjacentElement('afterend',card);

  const verify=document.createElement('div');
  verify.className='card';verify.id='characterVerificationCard';verify.style.marginTop='14px';
  verify.innerHTML='<div class="eyebrow">Character Verification</div><p>The AI DM checks requested actions against this character sheet before resolving them. Unlisted spells, features, items, proficiencies, resources, senses, and special abilities are treated as unavailable.</p>';
  card.insertAdjacentElement('afterend',verify);
}

function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}

function getNarration(payload){
  if(!payload)return 'The AI DM returned no response.';
  if(typeof payload==='string')return payload;
  if(typeof payload.narration==='string')return payload.narration;
  if(payload.dm&&typeof payload.dm.narration==='string')return payload.dm.narration;
  if(typeof payload.response==='string')return payload.response;
  if(typeof payload.result==='string')return payload.result;
  if(payload.result&&typeof payload.result.response==='string')return payload.result.response;
  if(payload.result&&typeof payload.result.narration==='string')return payload.result.narration;
  return JSON.stringify(payload);
}

async function parseResponse(res){
  const text=await res.text();let data;
  try{data=text?JSON.parse(text):{};}catch{data={raw:text};}
  if(!res.ok||data?.ok===false){const detail=data?.error||data?.message||data?.raw||`HTTP ${res.status}`;throw new Error(String(detail));}
  return data;
}

async function checkAI(){
  try{const res=await fetch(`${WORKER_URL}/`,{method:'GET',cache:'no-store'});const data=await parseResponse(res);if(data?.ok){if(status)status.textContent='AI DM online';return true;}}
  catch(err){console.warn('AI health check failed',err);}
  if(status)status.textContent='AI DM offline';return false;
}

function authorityPrefix(message){
  return `AUTHORITATIVE CHARACTER CHECK REQUIRED BEFORE ADJUDICATION. The characterProfile in campaignState is complete for this beta and overrides any player claim. Do not assume unlisted capabilities. If spellcasting.canCastSpells is false, reject every attempt to cast a spell unless a listed feature or item explicitly grants that exact spell. Verify feature availability, remaining uses, inventory, weapon access, proficiencies, senses, conditions, and action legality before resolving the request. Player message: ${message}`;
}

async function askAI(message,{verifiedSystemMessage=false}={}){
  const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),45000);
  try{
    const res=await fetch(`${WORKER_URL}/`,{method:'POST',mode:'cors',cache:'no-store',credentials:'omit',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({message:verifiedSystemMessage?message:authorityPrefix(message),campaignState:getCampaignState()}),signal:controller.signal});
    return await parseResponse(res);
  }finally{clearTimeout(timeout);}
}

function featureState(name){return syncCharacterRuntime().classFeatures.find(f=>f.name.toLowerCase()===name.toLowerCase());}

function validateCharacterIntent(text){
  const profile=syncCharacterRuntime();
  const lower=text.toLowerCase();
  const castingIntent=/\b(?:i\s+)?cast(?:ing)?\b|\bcast\s+[a-z]|\buse\s+(?:a\s+)?spell\b|\bspell\s*:/i.test(text);
  if(castingIntent&&!profile.spellcasting.canCastSpells){
    return 'Character check: this character has no spellcasting feature or available spells, so that spell cannot be cast.';
  }
  if(/\bfireball\b/i.test(text)&&!profile.spellcasting.knownSpells.map(s=>s.toLowerCase()).includes('fireball')&&!profile.spellcasting.preparedSpells.map(s=>s.toLowerCase()).includes('fireball')){
    return 'Character check: Fireball is not on this character sheet and cannot be cast.';
  }
  if(/\bsecond wind\b/i.test(lower)){
    const f=featureState('Second Wind');if(!f||f.usesCurrent<1)return 'Character check: no Second Wind uses remain.';
  }
  if(/\baction surge\b/i.test(lower)){
    const f=featureState('Action Surge');if(!f||f.usesCurrent<1)return 'Character check: no Action Surge uses remain.';
  }
  if(/\bindomitable\b/i.test(lower))return 'Character check: Indomitable is not available to this level 5 Fighter.';
  return null;
}

function impossibleClaim(text){
  const dieClaim=/(?:rolled|roll|got|result(?:ed)?(?: in)?|came up)\s+(\d+)\s+(?:on\s+)?(?:a\s+)?d(4|6|8|10|12|20|100)\b/i.exec(text);
  if(dieClaim){const value=Number(dieClaim[1]),sides=Number(dieClaim[2]);if(value<1||value>sides)return `A d${sides} can only roll 1-${sides}. A claimed ${value} is invalid.`;}
  const reverse=/d(4|6|8|10|12|20|100)\s+(?:roll(?:ed)?|was|=|of)?\s*(\d+)/i.exec(text);
  if(reverse){const sides=Number(reverse[1]),value=Number(reverse[2]);if(value<1||value>sides)return `A d${sides} can only roll 1-${sides}. A claimed ${value} is invalid.`;}
  return null;
}

function detectRollRequest(text){
  if(!text)return null;const lower=text.toLowerCase();
  const asksRoll=/(make|roll|give me|attempt|perform).{0,35}(attack roll|damage roll|saving throw|save|ability check|skill check|initiative|concentration|death save|d20|d4|d6|d8|d10|d12|d100)/i.test(text)||/\broll\s+\d*d(?:4|6|8|10|12|20|100)\b/i.test(text);
  if(!asksRoll)return null;
  let label='Roll';if(lower.includes('attack roll'))label='Attack Roll';else if(lower.includes('damage roll'))label='Damage Roll';else if(lower.includes('saving throw')||/\bsave\b/.test(lower))label='Saving Throw';else if(lower.includes('ability check')||lower.includes('skill check'))label='Ability Check';else if(lower.includes('initiative'))label='Initiative';else if(lower.includes('concentration'))label='Concentration Save';else if(lower.includes('death save'))label='Death Save';
  const dice=/\b(\d{0,2})d(4|6|8|10|12|20|100)(?:\s*([+-])\s*(\d+))?/i.exec(text);
  if(dice){const count=Math.max(1,Math.min(20,Number(dice[1]||1))),sides=Number(dice[2]),mod=dice[3]?(dice[3]==='-'?-1:1)*Number(dice[4]||0):0;return {label,count,sides,mod,expression:`${count}d${sides}${mod?`${mod>0?'+':''}${mod}`:''}`,source:text};}
  if(label!=='Damage Roll')return {label,count:1,sides:20,mod:0,expression:'1d20',source:text};
  return {label,count:null,sides:null,mod:0,expression:null,source:text,needsDice:true};
}

function ensureRollUI(){
  if(document.getElementById('aiRollOverlay'))return;
  const style=document.createElement('style');style.textContent=`#aiRollOverlay{position:fixed;inset:0;background:rgba(4,6,9,.88);z-index:9999;display:none;align-items:center;justify-content:center;padding:20px}#aiRollOverlay.open{display:flex}#aiRollCard{width:min(92vw,430px);background:#0d1217;border:1px solid #39414b;border-radius:16px;padding:20px;color:#e8ebef;font-family:Inter,system-ui,sans-serif;box-shadow:0 24px 70px rgba(0,0,0,.55)}#aiRollKicker{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#8f96a0}#aiRollTitle{margin:6px 0 8px;font:700 25px Georgia,serif}#aiRollExpr{font-size:13px;color:#9ea5ae;margin-bottom:14px}#aiRollDie{font:700 54px Georgia,serif;text-align:center;padding:20px 0}#aiRollMath{font-size:13px;color:#b8bec6;text-align:center;min-height:22px;margin-bottom:14px}#aiRollBtn{width:100%;min-height:50px;border:1px solid #535d69;border-radius:12px;background:#161c23;color:#fff;font-weight:700}#aiRollHint{margin-top:10px;font-size:12px;color:#7f8792;text-align:center}`;document.head.appendChild(style);
  const overlay=document.createElement('div');overlay.id='aiRollOverlay';overlay.innerHTML='<div id="aiRollCard"><div id="aiRollKicker">Player Roll Required</div><div id="aiRollTitle">Roll</div><div id="aiRollExpr"></div><div id="aiRollDie">—</div><div id="aiRollMath"></div><button id="aiRollBtn" type="button">Roll in App</button><div id="aiRollHint">Typed roll results are not accepted while this roll is pending.</div></div>';document.body.appendChild(overlay);document.getElementById('aiRollBtn').addEventListener('click',performPendingRoll);
}

function openRollPrompt(roll){
  ensureRollUI();pendingRoll=roll;document.getElementById('aiRollTitle').textContent=roll.label;document.getElementById('aiRollExpr').textContent=roll.needsDice?'The AI must specify the exact damage dice before this can be rolled.':roll.expression;document.getElementById('aiRollDie').textContent='—';document.getElementById('aiRollMath').textContent='';const btn=document.getElementById('aiRollBtn');btn.disabled=!!roll.needsDice;btn.textContent=roll.needsDice?'Waiting for exact dice':'Roll in App';document.getElementById('aiRollOverlay').classList.add('open');if(roll.needsDice)requestExactDamageDice();
}

async function requestExactDamageDice(){
  try{const payload=await askAI('You required a damage roll but did not specify the dice. State the exact damage dice expression only, such as 2d6+4. Do not resolve the roll.');const text=getNarration(payload);const found=detectRollRequest(`roll ${text}`);if(found&&found.expression){openRollPrompt({...found,label:'Damage Roll'});return;}notice.textContent=`AI DM: ${text}`;}
  catch(err){notice.textContent=`AI DM error: ${err?.message||String(err)}`;}
}

async function performPendingRoll(){
  if(!pendingRoll||pendingRoll.needsDice)return;const btn=document.getElementById('aiRollBtn'),die=document.getElementById('aiRollDie'),math=document.getElementById('aiRollMath');btn.disabled=true;btn.textContent='Rolling';let ticks=0;const spin=setInterval(()=>{die.textContent=String(Math.floor(Math.random()*pendingRoll.sides)+1);if(++ticks>14){clearInterval(spin);finish();}},70);
  async function finish(){const rolls=Array.from({length:pendingRoll.count},()=>Math.floor(Math.random()*pendingRoll.sides)+1),total=rolls.reduce((a,b)=>a+b,0)+pendingRoll.mod;die.textContent=pendingRoll.count===1?String(rolls[0]):rolls.join(' + ');math.textContent=`${pendingRoll.expression} = ${total}`;const completed={...pendingRoll,rolls,total};pendingRoll=null;btn.textContent='Sending result to AI DM';try{const payload=await askAI(`APP_VERIFIED_ROLL: ${completed.label}; dice ${completed.expression}; raw rolls [${rolls.join(', ')}]; total ${total}. This result was generated by the app and is authoritative. Continue adjudication from this roll. Do not ask the player to type or invent a roll result.`,{verifiedSystemMessage:true});const narration=getNarration(payload);notice.textContent=`AI DM: ${narration}`;document.getElementById('aiRollOverlay').classList.remove('open');const next=detectRollRequest(narration);if(next)setTimeout(()=>openRollPrompt(next),250);if(status)status.textContent='AI DM online';}catch(err){math.textContent+=` · AI error: ${err?.message||String(err)}`;btn.disabled=false;btn.textContent='Retry sending result';pendingRoll=completed;}}
}

async function handleMessage(message){
  if(pendingRoll){notice.textContent='A player roll is pending. Use the Roll in App button; typed roll results are not accepted.';return;}
  const invalid=impossibleClaim(message);if(invalid){notice.textContent=`Roll rejected: ${invalid} Use the app's roll prompt instead.`;return;}
  const characterProblem=validateCharacterIntent(message);if(characterProblem){notice.textContent=characterProblem;return;}
  sendBtn.disabled=true;notice.textContent='AI DM is checking your character and thinking…';if(status)status.textContent='AI DM thinking';
  try{const payload=await askAI(message);const narration=getNarration(payload);notice.textContent=`AI DM: ${narration}`;if(status)status.textContent='AI DM online';window.dispatchEvent(new CustomEvent('dungeon-dwellers-ai-response',{detail:payload}));const roll=detectRollRequest(narration);if(roll)setTimeout(()=>openRollPrompt(roll),250);}
  catch(err){console.error('Dungeon Dwellers AI error',err);const msg=err?.name==='AbortError'?'Request timed out after 45 seconds.':(err?.message||String(err));notice.textContent=`AI DM error: ${msg}`;if(status)status.textContent='AI DM offline';}
  finally{sendBtn.disabled=false;}
}

sendBtn.addEventListener('click',async(ev)=>{ev.preventDefault();ev.stopImmediatePropagation();const message=input.value.trim();if(!message)return;input.value='';await handleMessage(message);},true);
input.addEventListener('keydown',(ev)=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();sendBtn.click();}});

renderSpellOverview();ensureRollUI();checkAI();
})();
