(()=>{
'use strict';
if(window.__DD_CHARACTER_SYSTEM_V7)return;window.__DD_CHARACTER_SYSTEM_V7=true;
const $=(s,r=document)=>r.querySelector(s);
const DB=()=>window.DungeonDB,C=()=>window.ddSupabase||DB()?.client,campaignId=()=>localStorage.getItem('ddPreferredCampaign');
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function toast(text,type=''){const el=$('#toast');if(!el)return;el.textContent=text;el.className=`toast show ${type}`;clearTimeout(el._ddChar);el._ddChar=setTimeout(()=>el.className='toast',4500)}
function installStyles(){if($('#characterLibraryStyles'))return;const s=document.createElement('style');s.id='characterLibraryStyles';s.textContent=`.characterLibraryCard{margin-top:12px}.characterLibraryList{display:grid;gap:9px}.libraryCharacter{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid #765726;border-radius:13px;background:#080a0d;padding:12px}.libraryCharacter h3{margin:0;color:#ead098;font:500 18px Georgia,serif}.libraryCharacter p{margin:4px 0 0;color:#949ba4;font-size:11px}.libraryBadge{display:inline-block;margin-top:6px;border:1px solid #62491f;border-radius:999px;padding:3px 7px;color:#d4b873;font-size:9px}.libraryActions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.libraryEmpty{border:1px dashed #5c4523;border-radius:12px;padding:16px;color:#9198a1;text-align:center;font-size:11px}.completeSheet{margin-top:14px}.sheetSection{border-top:1px solid #3f321c;padding-top:15px;margin-top:15px}.sheetSection h3{font:500 18px Georgia,serif;color:#dfc17d}.sheetRaw{max-height:420px;overflow:auto;border:1px solid #5b4524;border-radius:12px;background:#050608;padding:10px;color:#aab0b8;font:10px/1.45 ui-monospace,monospace;white-space:pre-wrap;word-break:break-word}@media(max-width:640px){.libraryCharacter{grid-template-columns:1fr}.libraryActions{justify-content:stretch}.libraryActions button{flex:1}}`;document.head.appendChild(s)}
function ensureLibrary(){const page=$('#characterPage');if(!page||$('#characterLibraryCard'))return;const a=document.createElement('article');a.id='characterLibraryCard';a.className='card sectionCard characterLibraryCard';a.innerHTML='<div class="sectionHead"><div><div class="eyebrow">Your Account</div><h2>Character Library</h2></div></div><div id="characterLibraryList" class="characterLibraryList"><div class="libraryEmpty">Open this page to load saved characters.</div></div>';page.appendChild(a)}
function openPage(){($('.bottomNav [data-page="character"]')||$('.quickGrid [data-page="character"]'))?.click()}
function renderDetails(ch){const root=$('#characterContent'),p=ch?.profile;if(!root||!p)return;$('#completeImportedSheet')?.remove();const id=p.identity||{},d=p.defenses||{},meta=[id.class,id.subclass,id.level?`Level ${id.level}`:null,id.species||id.race].filter(Boolean).join(' · '),el=document.createElement('div');el.id='completeImportedSheet';el.className='completeSheet';el.innerHTML=`<section class="sheetSection"><div class="eyebrow">Selected Account Character</div><h2>${esc(id.name||ch.name||'Character')}</h2><p class="statusLine">${esc(meta||'Character')} · ${esc(d.armorClass!=null?`AC ${d.armorClass}`:'')} ${esc(d.maxHp!=null?`· ${d.maxHp} HP`:'')}</p></section><section class="sheetSection"><h3>Complete Character Data</h3><div class="sheetRaw">${esc(JSON.stringify(p,null,2))}</div></section>`;root.appendChild(el)}
async function libraryData(){const c=C();if(!c)return{chars:[],selected:null,user:null};const {data:s}=await c.auth.getSession(),user=s?.session?.user;if(!user)return{chars:[],selected:null,user:null};const {data:chars,error}=await c.from('account_characters').select('*').order('updated_at',{ascending:false});if(error)throw error;let selected=null,cid=campaignId();if(cid){const {data:e,error:se}=await c.from('campaign_character_selections').select('account_character_id').eq('campaign_id',cid).eq('user_id',user.id).maybeSingle();if(se)throw se;selected=e?.account_character_id||null}return{chars:chars||[],selected,user}}
async function renderLibrary(){ensureLibrary();const root=$('#characterLibraryList');if(!root)return;root.innerHTML='<div class="libraryEmpty">Loading saved characters...</div>';try{const {chars,selected}=await libraryData();if(!chars.length){root.innerHTML='<div class="libraryEmpty">No account characters yet. Tap Import PDF to add one.</div>';$('#completeImportedSheet')?.remove();return}root.innerHTML=chars.map(ch=>{const id=ch.profile?.identity||{},meta=[id.class,id.subclass,id.level?`Level ${id.level}`:null,id.species||id.race].filter(Boolean).join(' · ')||'Character',sel=selected===ch.id;return `<div class="libraryCharacter"><div><h3>${esc(ch.name)}</h3><p>${esc(meta)}</p><span class="libraryBadge">${sel?'Selected in this campaign':'Saved to your account'}</span></div><div class="libraryActions"><button class="${sel?'ghostBtn':'goldBtn'} librarySelect" data-id="${esc(ch.id)}" ${sel?'disabled':''}>${sel?'Selected':'Use in this campaign'}</button><button class="dangerBtn libraryDelete" data-id="${esc(ch.id)}" data-name="${esc(ch.name)}">Delete</button></div></div>`}).join('');if(selected){const current=chars.find(x=>x.id===selected);if(current)renderDetails(current)}}catch(e){root.innerHTML=`<div class="libraryEmpty">Could not load Character Library: ${esc(e.message||e)}</div>`}}
async function selectCharacter(id,{quiet=false,open=false}={}){const c=C(),db=DB(),cid=campaignId();if(!c||!db)throw new Error('Character system is not ready.');if(!cid)throw new Error('Open a campaign before selecting a character.');const {data:s}=await c.auth.getSession(),u=s?.session?.user;if(!u)throw new Error('Sign in first.');const {data:ch,error}=await c.from('account_characters').select('*').eq('id',id).eq('user_id',u.id).single();if(error)throw error;const importMeta={...(ch.import_meta||{}),account_character_id:ch.id};await db.saveCharacter(cid,{name:ch.name,display_name:ch.name,rules_edition:ch.rules_edition||'2024',profile:ch.profile||{},hp:ch.hp,max_hp:ch.max_hp,ac:ch.ac,source:ch.source||'account-library',import_meta:importMeta});const {error:se}=await c.from('campaign_character_selections').upsert({campaign_id:cid,user_id:u.id,account_character_id:ch.id,selected_at:new Date().toISOString()},{onConflict:'campaign_id,user_id'});if(se)throw se;if(open)openPage();renderDetails(ch);await renderLibrary();if(!quiet)toast(`${ch.name} is now selected for this campaign.`,'ok');window.dispatchEvent(new CustomEvent('dd:character-selected',{detail:{character:ch}}));return ch}
async function deleteCharacter(id,name){const c=C();if(!c)throw new Error('Character system is not ready.');const {data:s}=await c.auth.getSession(),u=s?.session?.user;if(!u)throw new Error('Sign in first.');const {data:ch,error}=await c.from('account_characters').select('id,name').eq('id',id).eq('user_id',u.id).single();if(error)throw error;name=ch.name||name||'this character';if(!window.confirm(`Delete ${name}?\n\nThis removes the saved character and removes it from any campaigns where you currently selected it. This cannot be undone.`))return;const {data:selections,error:selErr}=await c.from('campaign_character_selections').select('campaign_id').eq('account_character_id',id).eq('user_id',u.id);if(selErr)throw selErr;const campaignIds=(selections||[]).map(x=>x.campaign_id);for(const cid of campaignIds){const {error:ce}=await c.from('characters').delete().eq('campaign_id',cid).eq('user_id',u.id);if(ce)throw ce}const {error:sd}=await c.from('campaign_character_selections').delete().eq('account_character_id',id).eq('user_id',u.id);if(sd)throw sd;const {error:ad}=await c.from('account_characters').delete().eq('id',id).eq('user_id',u.id);if(ad)throw ad;$('#completeImportedSheet')?.remove();toast(`${name} was deleted.`,'ok');window.dispatchEvent(new CustomEvent('dd:character-deleted',{detail:{id,campaignIds}}));if(campaignIds.includes(campaignId()))setTimeout(()=>location.reload(),500);else await renderLibrary()}
document.addEventListener('click',async e=>{if(e.target?.closest?.('[data-page="character"]'))setTimeout(renderLibrary,0);const s=e.target?.closest?.('.librarySelect');if(s?.dataset.id)try{await selectCharacter(s.dataset.id,{open:true})}catch(x){toast(x.message||x,'bad')}const d=e.target?.closest?.('.libraryDelete');if(d?.dataset.id)try{await deleteCharacter(d.dataset.id,d.dataset.name)}catch(x){toast(`Could not delete character: ${x.message||x}`,'bad')}},true);
window.addEventListener('dd:campaign-changed',()=>{if($('#characterPage')?.classList.contains('active'))renderLibrary()});
window.addEventListener('dd:character-imported',e=>{const ch=e.detail?.character;if(ch){openPage();renderDetails(ch);renderLibrary()}});
installStyles();ensureLibrary();window.DungeonCharacterLibrary={render:renderLibrary,select:selectCharacter,delete:deleteCharacter,renderDetails,openPage};
})();