(()=>{
'use strict';
if(window.__DD_COMMUNITY_CHAT)return;window.__DD_COMMUNITY_CHAT=true;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const DB=()=>window.DungeonDB;
let uid=null,cid=null,members=[],selected=[],mode='party',refreshing=false;

function toast(text,type=''){const t=$('#toast');if(!t)return;t.textContent=text;t.className=`toast show ${type}`;clearTimeout(t._cc);t._cc=setTimeout(()=>t.className='toast',3000);}
function campaignId(){return localStorage.getItem('ddPreferredCampaign');}
async function waitReady(){for(let i=0;i<80;i++){const db=DB(),id=campaignId();if(db&&id){const s=await db.session().catch(()=>null);if(s?.user){uid=s.user.id;cid=id;return true;}}await new Promise(r=>setTimeout(r,200));}return false;}

function installStyles(){if($('#communityChatStyles'))return;const st=document.createElement('style');st.id='communityChatStyles';st.textContent=`
.sceneCard.communityChatCard{padding:14px;min-height:62vh;display:flex;flex-direction:column}.communityChatCard:before,.communityChatCard .sceneArt{display:none!important}.chatTop{display:flex;align-items:center;justify-content:space-between;gap:10px}.chatTabs{display:flex;gap:7px;flex-wrap:wrap}.chatTabs button{border:1px solid #343a43;background:#0d1116;color:#aeb4bd;border-radius:999px;padding:7px 10px;font-size:11px}.chatTabs button.active{border-color:#b58b46;color:#f0d38b;background:#17130c}.communityFeed{flex:1;min-height:320px;max-height:58vh;overflow:auto;display:flex;flex-direction:column;gap:9px;padding:12px 2px}.communityMsg{max-width:88%;border:1px solid #2c3239;border-radius:15px;background:#0d1014;padding:10px 12px}.communityMsg.mine{align-self:flex-end;border-color:#6c5734;background:#17130d}.communityMsg.dm{align-self:flex-start;border-color:#8a6c38;background:linear-gradient(145deg,#19150d,#0e1013);box-shadow:0 0 18px rgba(214,171,88,.08)}.communityMsg.private{border-style:dashed}.communityMsg strong{display:block;font-size:11px;color:#e8d19d}.communityMsg span{display:block;margin-top:4px;white-space:pre-wrap;line-height:1.48;font-size:13px}.communityMsg small{display:block;margin-top:5px;color:#777f89;font-size:9px}.communityComposer{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end;border-top:1px solid #282e35;padding-top:10px}.communityComposer textarea{min-height:46px;max-height:120px;resize:vertical}.communityActions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.recipientLine{font-size:10px;color:#aeb4bd;margin-top:5px}.recipientLine button{border:0;background:none;color:#e0bd78;padding:0;text-decoration:underline}.sceneCard.communityChatCard #sceneTitle,.sceneCard.communityChatCard #sceneText{display:none!important}
`;document.head.appendChild(st);}

async function loadMembers(){const [rows,chars]=await Promise.all([DB().members(cid),DB().memberCharacters(cid)]);const names=new Map(chars.map(c=>[c.user_id,c.display_name||c.name||'Player']));members=rows.filter(r=>r.user_id!==uid).map(r=>({id:r.user_id,name:names.get(r.user_id)||`Player ${String(r.user_id).slice(0,4)}`}));}
function memberName(id){if(id===uid)return 'You';return members.find(m=>m.id===id)?.name||`Player ${String(id||'').slice(0,4)}`;}

function renderShell(){const card=$('.sceneCard');if(!card)return false;card.classList.add('communityChatCard');card.innerHTML=`
<div class="chatTop"><div><div class="eyebrow">Adventure Chat</div><h2 style="margin:4px 0 0;font-family:Georgia,serif">Party & AI Dungeon Master</h2></div><div class="chatTabs"><button id="ccParty" class="active">Party</button><button id="ccPrivate">Direct Messages</button></div></div>
<div id="ccRecipientLine" class="recipientLine">Everyone in the campaign can see Party chat.</div>
<div id="communityFeed" class="communityFeed"></div>
<div class="communityComposer"><textarea id="communityInput" class="field" maxlength="4000" placeholder="Message the party..."></textarea><button id="communitySend" class="sendBtn" aria-label="Send">›</button></div>
<div class="communityActions"><button id="communityAskDM" class="goldBtn">Ask AI DM</button><button id="communityChoosePeople" class="ghostBtn hidden">Choose Players</button></div>
<div id="sceneNotice" class="sceneNotice">Party chat is free conversation. Use Ask AI DM when you want the Dungeon Master to respond.</div>
<span id="sceneTitle" hidden></span><span id="sceneText" hidden></span>`;
$('#continueTurn')?.classList.add('hidden');
$('#partyChatCard')?.remove();
$('#ccParty').onclick=()=>setMode('party');$('#ccPrivate').onclick=()=>setMode('private');
$('#communitySend').onclick=()=>send(false);$('#communityAskDM').onclick=()=>send(true);$('#communityChoosePeople').onclick=openPeople;
$('#communityInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(false);}});
return true;}

function setMode(next){mode=next;$('#ccParty')?.classList.toggle('active',mode==='party');$('#ccPrivate')?.classList.toggle('active',mode==='private');$('#communityChoosePeople')?.classList.toggle('hidden',mode!=='private');const input=$('#communityInput');if(input)input.placeholder=mode==='party'?'Message the party...':'Private message...';updateRecipientLine();renderFeed();}
function updateRecipientLine(){const line=$('#ccRecipientLine');if(!line)return;if(mode==='party'){line.textContent='Everyone in the campaign can see Party chat.';return;}if(!selected.length){line.innerHTML='Direct Message inbox · <button id="ccPickInline">choose players to start a conversation</button>';$('#ccPickInline').onclick=openPeople;return;}line.innerHTML=`Private with ${selected.map(id=>esc(memberName(id))).join(', ')} · <button id="ccPickInline">change</button>`;$('#ccPickInline').onclick=openPeople;}
function openPeople(){const root=$('#modalRoot');if(!root)return;root.classList.remove('hidden');root.innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="eyebrow">Direct Messages</div><h2>Choose players</h2><p>Select one or more players. Only you, those players, and private AI DM replies in this conversation can see these messages.</p><div class="toggleList">${members.map(m=>`<label class="toggleRow"><span>${esc(m.name)}</span><input type="checkbox" data-cc-user="${m.id}" ${selected.includes(m.id)?'checked':''}></label>`).join('')||'<div class="statusLine">No other players have joined yet.</div>'}</div><div class="buttonRow" style="margin-top:14px"><button id="ccPeopleCancel" class="ghostBtn">Cancel</button><button id="ccPeopleSave" class="goldBtn">Open Conversation</button></div></div></div>`;$('#ccPeopleCancel').onclick=()=>{root.classList.add('hidden');root.innerHTML='';};$('#ccPeopleSave').onclick=()=>{selected=[...root.querySelectorAll('[data-cc-user]:checked')].map(x=>x.dataset.ccUser);root.classList.add('hidden');root.innerHTML='';updateRecipientLine();renderFeed();};}

function participants(m){return new Set([m.user_id,...(m.recipient_user_ids||[])].filter(Boolean));}
function sameConversation(m){if(m.visibility!=='private')return false;if(!selected.length)return true;const want=new Set([uid,...selected]),got=participants(m);if(want.size!==got.size)return false;for(const x of want)if(!got.has(x))return false;return true;}
async function renderFeed(){if(refreshing||!cid||!$('#communityFeed'))return;refreshing=true;try{const msgs=await DB().chat(cid,200);const shown=msgs.filter(m=>mode==='party'?m.visibility!=='private':sameConversation(m));const root=$('#communityFeed');root.innerHTML=shown.map(m=>{const dm=m.sender_kind==='dm',mine=m.user_id===uid,label=dm?'AI Dungeon Master':memberName(m.user_id);const privateLabel=m.visibility==='private'?` · Private${m.recipient_user_ids?.length?` with ${[...participants(m)].filter(x=>x!==uid).map(memberName).join(', ')}`:''}`:'';return `<div class="communityMsg ${mine?'mine':''} ${dm?'dm':''} ${m.visibility==='private'?'private':''}"><strong>${esc(label)}${esc(privateLabel)}</strong><span>${esc(m.body)}</span><small>${new Date(m.created_at).toLocaleString()}</small></div>`;}).join('')||`<div class="statusLine">${mode==='party'?'No messages yet. Start the adventure together.':'No private messages in this conversation yet.'}</div>`;root.scrollTop=root.scrollHeight;}catch(e){toast(e.message||String(e),'bad');}finally{refreshing=false;}}

async function insertPlayerMessage(body){const row={campaign_id:cid,user_id:uid,sender_kind:'player',visibility:mode,recipient_user_ids:mode==='private'?selected:[],body,mentions:[],metadata:{source:'community-chat'}};const {error}=await DB().client.from('chat_messages').insert(row);if(error)throw error;}
async function send(askDM){const input=$('#communityInput');if(!input)return;const body=input.value.trim();if(!body)return;if(mode==='private'&&!selected.length){toast('Choose at least one player for a private conversation.','warn');openPeople();return;}input.value='';try{await insertPlayerMessage(body);await renderFeed();if(askDM){const btn=$('#communityAskDM');if(btn){btn.disabled=true;btn.textContent='AI DM responding...';}const {data,error}=await DB().client.functions.invoke('dungeon-chat',{body:{campaignId:cid,message:body,visibility:mode,recipientUserIds:mode==='private'?selected:[]}});if(error)throw error;if(data?.ok===false)throw new Error(data.error||'AI DM failed');await renderFeed();if(btn){btn.disabled=false;btn.textContent='Ask AI DM';}}}catch(e){toast(e.message||String(e),'bad');const btn=$('#communityAskDM');if(btn){btn.disabled=false;btn.textContent='Ask AI DM';}}}

async function init(){if(!await waitReady())return;installStyles();await loadMembers().catch(()=>{});for(let i=0;i<30&&!renderShell();i++)await new Promise(r=>setTimeout(r,150));updateRecipientLine();await renderFeed();setInterval(()=>{const next=campaignId();if(next&&next!==cid){cid=next;selected=[];loadMembers().then(renderFeed).catch(()=>{});}else renderFeed();},2000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,400));else setTimeout(init,400);
})();