(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB=()=>window.DungeonDB;
let currentCampaignId=null,currentUser=null,refreshTimer=null;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
async function session(){try{return await DB()?.session();}catch{return null;}}
function campaignId(){return localStorage.getItem('ddPreferredCampaign')||currentCampaignId;}
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.className='toast show';clearTimeout(t._rt);t._rt=setTimeout(()=>t.className='toast',3000);}
async function waitForCampaign(){for(let i=0;i<80;i++){const s=await session();if(s){currentUser=s.user;const id=campaignId();if(id){currentCampaignId=id;return true;}}await new Promise(r=>setTimeout(r,250));}return false;}
async function ensureSceneTurnUI(){if($('#sceneTurnPanel'))return;const continueBtn=$('#continueTurn');if(!continueBtn)return;const panel=document.createElement('article');panel.id='sceneTurnPanel';panel.className='card sectionCard sceneTurnPanel';panel.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">Scene Turn</div><h2>Asynchronous Exploration</h2></div><span id="sceneTurnState" class="tag">Loading</span></div><p class="statusLine">Outside combat, each player may submit one meaningful scene action. Questions about known rules, inventory and party discussion remain free. The AI DM resolves submitted actions together.</p><div class="buttonRow"><button id="submitSceneAction" class="goldBtn">Submit Scene Action</button><button id="checkSceneSubmission" class="ghostBtn">View My Submission</button></div>`;continueBtn.insertAdjacentElement('afterend',panel);$('#submitSceneAction').onclick=openSceneSubmission;$('#checkSceneSubmission').onclick=showMySceneSubmission;await renderSceneTurnState();}
async function renderSceneTurnState(){const id=campaignId(),el=$('#sceneTurnState');if(!id||!el)return;try{const c=await DB().campaign(id),num=Number(c.state?.scene_turn_number||1);el.textContent=c.active_block?`Combat · ${c.active_block}`:`Scene ${num}`;$('#submitSceneAction').disabled=!!c.active_block||!!c.paused;}catch{el.textContent='Unavailable';}}
async function openSceneSubmission(){const id=campaignId();if(!id)return;const c=await DB().campaign(id);if(c.active_block){toast('Combat is active. Use the combat turn submission.');return;}if(c.paused){toast('Campaign progression is paused.');return;}const num=Number(c.state?.scene_turn_number||1),existing=await DB().mySceneSubmission(id,num).catch(()=>null),root=$('#modalRoot');root.classList.remove('hidden');root.innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="eyebrow">Scene Turn ${num}</div><h2>Submit your meaningful action</h2><p>Describe one meaningful action. You may include a fallback or condition. Do not type a die result; if a roll is needed the app/AI flow should request it.</p><label class="fieldLabel">Action<textarea id="sceneActionText" rows="6">${esc(existing?.action?.text||'')}</textarea></label><div class="buttonRow" style="margin-top:12px"><button id="sceneCancel" class="ghostBtn">Cancel</button><button id="sceneSave" class="goldBtn">${existing?'Update':'Submit'} Action</button></div></div></div>`;$('#sceneCancel').onclick=()=>{root.classList.add('hidden');root.innerHTML='';};$('#sceneSave').onclick=async()=>{const text=$('#sceneActionText').value.trim();if(!text)return;try{await DB().submitScene(id,num,{text,status:'submitted'});root.classList.add('hidden');root.innerHTML='';toast('Scene action submitted. The AI DM can resolve early when everyone is ready.');}catch(e){toast(e.message||String(e));}};}
async function showMySceneSubmission(){const id=campaignId();if(!id)return;const c=await DB().campaign(id),num=Number(c.state?.scene_turn_number||1),row=await DB().mySceneSubmission(id,num).catch(()=>null);toast(row?.action?.text?`Scene ${num}: ${row.action.text}`:`No scene action submitted for Scene ${num}.`);}
async function ensureChat(){if($('#partyChatCard'))return;const page=$('#campaignPage');if(!page)return;const card=document.createElement('article');card.id='partyChatCard';card.className='card sectionCard';card.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">Party Chat</div><h2>In-Character / Party Discussion</h2></div><button id="refreshChat" class="ghostBtn">Refresh</button></div><div id="partyChatList" class="chatList"></div><div class="composer chatComposer"><input id="partyChatInput" maxlength="2000" placeholder="Message the party..."><button id="partyChatSend" class="sendBtn" aria-label="Send">›</button></div><p class="statusLine">Party discussion does not spend a scene action. Use @name mentions when useful.</p>`;page.appendChild(card);$('#refreshChat').onclick=renderChat;$('#partyChatSend').onclick=sendChat;$('#partyChatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat();}});await renderChat();}
async function renderChat(){const id=campaignId(),root=$('#partyChatList');if(!id||!root)return;try{const [msgs,chars]=await Promise.all([DB().chat(id,100),DB().memberCharacters(id)]),names=new Map(chars.map(c=>[c.user_id,c.display_name||c.name||'Player']));root.innerHTML=msgs.map(m=>`<div class="chatBubble ${m.user_id===currentUser?.id?'mine':''}"><strong>${esc(names.get(m.user_id)||'Player')}</strong><span>${esc(m.body)}</span><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<div class="statusLine">No party messages yet.</div>';root.scrollTop=root.scrollHeight;}catch(e){root.innerHTML=`<div class="statusLine">${esc(e.message||e)}</div>`;}}
async function sendChat(){const id=campaignId(),input=$('#partyChatInput');if(!id||!input)return;const body=input.value.trim();if(!body)return;input.value='';try{const chars=await DB().memberCharacters(id),mentions=chars.filter(c=>body.toLowerCase().includes('@'+String(c.display_name||c.name||'').toLowerCase())).map(c=>c.user_id);await DB().sendChat(id,body,mentions);await renderChat();}catch(e){toast(e.message||String(e));}}
async function enhanceMapViews(){const id=campaignId();if(!id||!currentUser)return;let map,tokens,view,character;try{[map,tokens,character]=await Promise.all([DB().activeMap(id),DB().tokens(id),DB().character(id)]);view=map?await DB().mapView(map.id):null;}catch{return;}const own=tokens.find(t=>t.owner_user_id===currentUser.id)||tokens.find(t=>t.character_id===character?.id),v=view?.view_state||{};for(const frame of $$('.mapFrame')){frame.querySelectorAll('.playerVisionLabel,.privateVisionOverlay').forEach(e=>e.remove());const label=document.createElement('div');label.className='playerVisionLabel';label.textContent=v.mode==='shared'?'Shared Party Vision':v.mode==='explored'?'Explored + Current Vision':'Your Current Vision';frame.appendChild(label);const overlay=document.createElement('canvas');overlay.className='privateVisionOverlay';frame.appendChild(overlay);const draw=()=>{const r=frame.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);overlay.width=Math.max(1,Math.floor(r.width*dpr));overlay.height=Math.max(1,Math.floor(r.height*dpr));overlay.style.width=r.width+'px';overlay.style.height=r.height+'px';const ctx=overlay.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='rgba(0,0,0,.74)';ctx.fillRect(0,0,r.width,r.height);ctx.globalCompositeOperation='destination-out';const visible=Array.isArray(v.visible)?v.visible:[];if(visible.length){for(const region of visible){if(region?.type==='circle'){const x=r.width*(Number(region.x)||50)/100,y=r.height*(Number(region.y)||50)/100,rad=Math.max(20,r.width*(Number(region.radius)||16)/100),g=ctx.createRadialGradient(x,y,rad*.55,x,y,rad);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();}}}else{const x=r.width*(Number(own?.x)||50)/100,y=r.height*(Number(own?.y)||50)/100,base=character?.profile?.senses?.darkvision?20:15,rad=Math.max(70,r.width*base/100),g=ctx.createRadialGradient(x,y,rad*.58,x,y,rad);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';};draw();overlay._draw=draw;}}
async function ensureControlledUnits(){const root=$('#characterContent');if(!root||$('#controlledUnitsFinal'))return;const id=campaignId();if(!id)return;try{const tokens=await DB().tokens(id),mine=tokens.filter(t=>t.owner_user_id===currentUser?.id&&t.token_type!=='pc'),card=document.createElement('div');card.id='controlledUnitsFinal';card.innerHTML=`<div class="eyebrow" style="margin-top:18px">Controlled Units</div><div class="list">${mine.map(t=>`<div class="listItem"><strong>${esc(t.name||'Controlled Unit')}</strong><span>${esc(t.token_type)} · directly controlled by you; AI handles legal math and consequences.</span></div>`).join('')||'<div class="statusLine">No companions, familiars, summons, or mounts are active.</div>'}</div>`;root.appendChild(card);}catch{}}
function observe(){const obs=new MutationObserver(()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{renderSceneTurnState();if($('#campaignPage.active'))renderChat();enhanceMapViews();ensureControlledUnits();},120);});obs.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',()=>$$('.privateVisionOverlay').forEach(c=>c._draw?.()));}
async function init(){if(window.__DD_FINAL_RUNTIME_STARTED)return;window.__DD_FINAL_RUNTIME_STARTED=true;if(!await waitForCampaign()){window.__DD_FINAL_RUNTIME_STARTED=false;return;}await ensureSceneTurnUI();await ensureChat();await enhanceMapViews();await ensureControlledUnits();observe();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250));else setTimeout(init,250);
})();