(()=>{
'use strict';
if(window.__DD_INTERACTION_UI_V1)return;window.__DD_INTERACTION_UI_V1=true;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function specFor(map){const s=map?.generated_spec||{};return{widthCells:Number(s.widthCells||map?.width||30),heightCells:Number(s.heightCells||map?.height||22)};}
function tokenPos(t,s){let x=Number(t?.x),y=Number(t?.y);if(!Number.isFinite(x))x=s.widthCells/2;if(!Number.isFinite(y))y=s.heightCells/2;const grid=t?.state?.position_mode==='grid'||(x<=s.widthCells&&y<=s.heightCells);if(!grid){x=x/100*s.widthCells;y=y/100*s.heightCells;}return{x:clamp(x,0,s.widthCells),y:clamp(y,0,s.heightCells)};}
function installStyles(){if(document.getElementById('ddInteractionUiStyles'))return;const s=document.createElement('style');s.id='ddInteractionUiStyles';s.textContent=`.communityComposer{grid-template-columns:minmax(0,1fr) 48px!important;align-items:stretch!important}.communityComposer textarea{width:100%!important;min-width:0!important;box-sizing:border-box!important}.communitySendBtn{width:48px!important;min-width:48px!important;max-width:48px!important;height:48px!important;min-height:48px!important;align-self:end!important;padding:0!important;display:grid!important;place-items:center!important;border:1px solid #c99c4c!important;border-radius:14px!important;background:linear-gradient(#f1cc75,#b98533)!important;color:#171108!important;font-size:28px!important;font-weight:900!important;line-height:1!important;box-shadow:0 0 22px rgba(214,171,88,.24)!important}.ddTokenPanel{position:absolute;z-index:9;left:10px;right:10px;bottom:10px;border:1px solid #8c6a32;border-radius:13px;background:rgba(7,9,12,.96);box-shadow:0 12px 30px rgba(0,0,0,.46);padding:10px}.ddTokenPanelTop{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.ddTokenPanel strong{display:block;color:#f0d38d;font-size:13px}.ddTokenPanel small{display:block;color:#8e959d;font-size:9px;margin-top:3px;text-transform:uppercase;letter-spacing:.08em}.ddTokenPanelActions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.ddTokenPanel button{border:1px solid #71572f;border-radius:10px;background:#11151a;color:#e5d5ad;padding:7px 10px;font-size:10px;font-weight:800}.ddTokenPanel button.primary{background:#c99c4c;color:#171006;border-color:#c99c4c}.ddTokenPanel button.close{margin-left:auto;border:0;background:transparent;color:#9ba2aa;padding:2px 4px}.ddTokenSelectedRing{position:absolute;z-index:7;border:2px solid #f0c96f;border-radius:50%;box-shadow:0 0 14px rgba(240,201,111,.65);pointer-events:none;transform:translate(-50%,-50%)}@media(max-width:420px){.communityComposer{grid-template-columns:minmax(0,1fr) 46px!important;gap:7px!important}.communitySendBtn{width:46px!important;min-width:46px!important;max-width:46px!important;height:46px!important;min-height:46px!important}}`;document.head.appendChild(s);}
function replaceChatSendButton(){const b=document.getElementById('communitySend');if(!b)return;b.classList.remove('sendBtn');b.classList.add('communitySendBtn');b.setAttribute('aria-label','Send message');b.textContent='›';}
function closePanel(frame){frame?.querySelectorAll('.ddTokenPanel,.ddTokenSelectedRing').forEach(e=>e.remove());}
function runPublicAction(text){document.getElementById('ccParty')?.click();setTimeout(()=>{const input=document.getElementById('communityInput'),ask=document.getElementById('communityAskDM');if(!input||!ask)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));ask.click();},0);}
function openCharacter(){document.querySelector('.bottomNav [data-page="character"],.quick[data-page="character"]')?.click();}
function showPanel(frame,token,opts,hit){closePanel(frame);const wrap=frame.querySelector('.ddMapCanvasWrap');if(!wrap)return;const ring=document.createElement('div');ring.className='ddTokenSelectedRing';ring.style.left=`${hit.x}px`;ring.style.top=`${hit.y}px`;ring.style.width=`${hit.size}px`;ring.style.height=`${hit.size}px`;wrap.appendChild(ring);const panel=document.createElement('div');panel.className='ddTokenPanel';const own=token.owner_user_id===opts.userId||token.character_id===opts.characterId,type=String(token.token_type||'token').toLowerCase(),name=String(token.name||'Token');let actions='';if(own)actions='<button class="primary" data-action="character">Open Character</button>';else if(type==='enemy')actions=`<button class="primary" data-action="attack">Attack ${esc(name)}</button><button data-action="target">Name as Target</button>`;else if(type==='npc')actions=`<button class="primary" data-action="talk">Talk to ${esc(name)}</button><button data-action="target">Interact</button>`;else actions=`<button class="primary" data-action="target">Interact with ${esc(name)}</button>`;panel.innerHTML=`<div class="ddTokenPanelTop"><div><strong>${esc(name)}</strong><small>${own?'Your token':type}</small></div><button class="close" data-action="close" aria-label="Close token panel">✕</button></div><div class="ddTokenPanelActions">${actions}</div>`;wrap.appendChild(panel);panel.querySelector('[data-action="close"]')?.addEventListener('click',()=>closePanel(frame));panel.querySelector('[data-action="character"]')?.addEventListener('click',openCharacter);panel.querySelector('[data-action="attack"]')?.addEventListener('click',()=>runPublicAction(`I attack ${name}.`));panel.querySelector('[data-action="talk"]')?.addEventListener('click',()=>runPublicAction(`I speak to ${name}.`));panel.querySelector('[data-action="target"]')?.addEventListener('click',()=>{document.getElementById('ccParty')?.click();setTimeout(()=>{const input=document.getElementById('communityInput');if(!input)return;input.value=type==='enemy'?`I target ${name}.`:`I interact with ${name}.`;input.focus();},0);});}
function attach(frame,opts){const canvas=frame.querySelector('.ddMapCanvas');if(!canvas||!opts?.map||canvas.dataset.ddTokenInteraction==='1')return;canvas.dataset.ddTokenInteraction='1';const mapTokens=(opts.tokens||[]).filter(t=>!t.map_id||t.map_id===opts.map.id),s=specFor(opts.map);let down=null,moved=false;const coords=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,w:r.width,h:r.height};};const hitAt=e=>{const p=coords(e),scaleX=p.w/s.widthCells,scaleY=p.h/s.heightCells;let best=null;for(const t of mapTokens){const tp=tokenPos(t,s),x=tp.x*scaleX,y=tp.y*scaleY,d=Math.hypot(p.x-x,p.y-y),radius=Math.max(18,Math.min(scaleX,scaleY)*.55);if(d<=radius&&(!best||d<best.d))best={token:t,d,x,y,size:radius*2};}return best;};canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};moved=false;},{capture:true});canvas.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)moved=true;},{capture:true});canvas.addEventListener('pointerup',e=>{const wasMoved=moved;down=null;moved=false;if(wasMoved)return;const hit=hitAt(e);if(hit)showPanel(frame,hit.token,opts,hit);else closePanel(frame);});const tip=frame.querySelector('.ddMapTip');if(tip)tip.textContent=mapTokens.some(t=>t.owner_user_id===opts.userId)?'Tap tokens for actions · drag your token to move':'Tap tokens for actions · 5 ft tactical grid';}
function patchMap(){const engine=window.DungeonMapEngine;if(!engine?.renderTactical||engine.__ddTokenInteractionsPatched)return false;engine.__ddTokenInteractionsPatched=true;const original=engine.renderTactical.bind(engine);engine.renderTactical=function(frame,opts={}){const out=original(frame,opts);attach(frame,opts);return out;};return true;}
function init(){installStyles();replaceChatSendButton();patchMap();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.addEventListener('load',()=>{replaceChatSendButton();patchMap();},{once:true});
})();