(()=>{
'use strict';
if(window.__DD_INVENTORY_SYSTEM_V1)return;window.__DD_INVENTORY_SYSTEM_V1=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB=()=>window.DungeonDB;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const campaignId=()=>localStorage.getItem('ddPreferredCampaign');
let lastCharacter=null,rendering=false,observer=null;
function installStyles(){if($('#ddInventoryStyles'))return;const s=document.createElement('style');s.id='ddInventoryStyles';s.textContent=`
.ddInventoryEnhanced{display:grid;gap:10px}.ddInventoryHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;margin-bottom:2px}.ddInventoryHead h3{margin:3px 0 0;color:#efd18c;font:500 22px Georgia,serif}.ddInventoryHead span{color:#8e959d;font-size:10px}.ddInventoryItem{border:1px solid #6d5125;border-radius:13px;background:#080a0d;overflow:hidden}.ddInventoryItem[open]{border-color:#a47b37}.ddInventoryItem summary{list-style:none;cursor:pointer;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px}.ddInventoryItem summary::-webkit-details-marker{display:none}.ddInventoryItem summary strong{color:#e5c77e;font-size:13px}.ddInventoryItem summary small{display:block;margin-top:3px;color:#8f969e;font-size:10px}.ddInvBadge{border:1px solid #705426;border-radius:999px;padding:4px 7px;color:#d8bd7c;font-size:9px;text-transform:uppercase}.ddInventoryBody{border-top:1px solid #3d301b;padding:11px 12px 13px;display:grid;gap:8px}.ddInventoryStats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ddInventoryStat{border:1px solid #3e321f;border-radius:9px;background:#050608;padding:8px}.ddInventoryStat b{display:block;color:#d9bd7a;font-size:9px;text-transform:uppercase}.ddInventoryStat span{display:block;margin-top:3px;color:#d7dbe0;font-size:12px}.ddAttackReady{border:1px solid #9b7535;border-radius:9px;padding:9px;color:#efce83;background:#110d06;font-size:10px}.ddInventoryNotes{color:#afb5bc;font-size:11px;line-height:1.45;white-space:pre-wrap}@media(max-width:560px){.ddInventoryHead{align-items:flex-start;flex-direction:column}.ddInventoryStats{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function categoryLabel(i){return i.category==='weapon'?'Weapon':i.category==='armor'?'Armor':i.category==='consumable'?'Consumable':i.category==='magic'?'Magic Item':'Gear'}
function itemSummary(i){const bits=[];if(i.quantity!=null)bits.push(`Qty ${i.quantity}`);if(i.damage)bits.push(i.damage);else if(i.effect)bits.push(i.effect);if(i.weight)bits.push(i.weight);return bits.join(' · ')||categoryLabel(i)}
function stat(label,value){if(value==null||value==='')return'';return `<div class="ddInventoryStat"><b>${esc(label)}</b><span>${esc(value)}</span></div>`}
function itemsFromProfile(p){const eq=p?.equipment||{};return [...(eq.weapons||[]),...(eq.armor||[]),...(eq.consumables||[]),...(eq.magicItems||[]),...(eq.gear||[])];}
function renderFromCharacter(ch){const root=$('#inventoryContent');if(!root||!ch?.profile)return;rendering=true;try{lastCharacter=ch;const p=ch.profile,items=itemsFromProfile(p),name=ch.name||p.identity?.name||'Character';root.innerHTML=`<div class="ddInventoryEnhanced"><div class="ddInventoryHead"><div><div class="eyebrow">Character Inventory</div><h3>${esc(name)}</h3></div><span>${items.length} item${items.length===1?'':'s'} · tap an item for details</span></div>${items.map(i=>`<details class="ddInventoryItem"><summary><div><strong>${esc(i.name||'Item')}</strong><small>${esc(itemSummary(i))}</small></div><span class="ddInvBadge">${esc(categoryLabel(i))}</span></summary><div class="ddInventoryBody"><div class="ddInventoryStats">${stat('Quantity',i.quantity)}${stat('Weight',i.weight)}${stat('Damage',i.damage)}${stat('Range',i.range)}${stat('Attack Bonus',i.attackBonus)}${stat('Properties',i.properties||i.rulesProfile)}${stat('Damage Type',i.damageType)}</div>${i.category==='weapon'?'<div class="ddAttackReady">Available in the Attack action weapon selector.</div>':''}${i.effect||i.notes?`<div class="ddInventoryNotes">${esc(i.effect||i.notes)}</div>`:''}</div></details>`).join('')||'<div class="statusLine">No inventory is recorded on the selected character.</div>'}</div>`;}finally{rendering=false}}
async function loadCharacter(){const id=campaignId(),db=DB();if(!id||!db)return null;try{return await db.character(id)}catch(e){console.warn('Inventory load failed',e);return null}}
async function render(){const ch=await loadCharacter();if(ch)renderFromCharacter(ch)}
function observeInventory(){const root=$('#inventoryContent');if(!root||observer)return;observer=new MutationObserver(()=>{if(rendering||!lastCharacter||!$('#inventoryPage')?.classList.contains('active'))return;if(!root.querySelector('.ddInventoryEnhanced'))renderFromCharacter(lastCharacter)});observer.observe(root,{childList:true});}
document.addEventListener('click',e=>{if(e.target?.closest?.('[data-page="inventory"]'))setTimeout(render,0)},true);
window.addEventListener('dd:character-selected',()=>setTimeout(render,0));
window.addEventListener('dd:character-imported',()=>setTimeout(render,0));
window.addEventListener('dd:character-deleted',()=>{lastCharacter=null;setTimeout(render,0)});
function init(){installStyles();observeInventory();if($('#inventoryPage')?.classList.contains('active'))render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80));else setTimeout(init,80);
window.DungeonInventoryUI={render};
})();