(()=>{
'use strict';
if(window.__DD_MAP_ENGINE_V2)return;window.__DD_MAP_ENGINE_V2=true;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hash=s=>{let h=2166136261>>>0;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
const rng=seed=>{let x=(seed||1)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000;};};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function injectStyles(){if(document.getElementById('ddMapEngineStyles'))return;const s=document.createElement('style');s.id='ddMapEngineStyles';s.textContent=`.ddMapShell{position:relative;width:100%;min-height:280px;border-radius:14px;overflow:hidden;background:#090c10;border:1px solid rgba(210,180,110,.2)}.ddMapToolbar{display:flex;gap:8px;align-items:center;padding:8px 9px;background:#0d1117;border-bottom:1px solid rgba(210,180,110,.16);position:relative;z-index:3}.ddMapToolbar button{border:1px solid #57472d;background:#131820;color:#c9c2b4;border-radius:999px;padding:6px 10px;font-size:10px;font-weight:800;letter-spacing:.04em}.ddMapToolbar button.active{background:#2a1d08;border-color:#d4ad53;color:#ffe3a0}.ddMapToolbar .ddMapLocation{margin-left:auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#8f98a3;font-size:10px}.ddMapCanvasWrap{position:relative;min-height:270px;touch-action:none;overflow:hidden}.ddMapCanvasWrap.ddWorldMapWrap{background:#272317}.ddMapCanvas{display:block;width:100%;height:auto;min-height:270px;background:#090c10;touch-action:none}.ddMapEmpty{min-height:270px;display:grid;place-items:center;text-align:center;padding:26px;color:#929aa4}.ddMapEmpty strong{display:block;color:#e3c982;font-size:16px;margin-bottom:5px}.ddMapTip{position:absolute;left:10px;bottom:10px;background:rgba(7,9,12,.86);border:1px solid rgba(210,180,110,.2);border-radius:8px;padding:5px 8px;font-size:9px;color:#aeb5bd;pointer-events:none}.ddMapVision{position:absolute;right:66px;top:10px;z-index:2;max-width:calc(100% - 86px);background:rgba(7,9,12,.88);border:1px solid rgba(233,201,126,.42);border-radius:999px;padding:5px 9px;font-size:9px;font-weight:800;letter-spacing:.03em;color:#e8d39b;pointer-events:none;white-space:nowrap}`;document.head.appendChild(s);}
function starterSpec(seedText='',name='Generated Location'){
 const widthCells=30,heightCells=22,cellSizeFt=5,r=rng(hash(seedText+'|'+name)),regions=[];let x=2+Math.floor(r()*3),y=6+Math.floor(r()*5),prev=null;const count=3+Math.floor(r()*3);
 for(let i=0;i<count;i++){const w=5+Math.floor(r()*5),h=4+Math.floor(r()*4);x=clamp(x+(i?3+Math.floor(r()*5):0),1,widthCells-w-1);y=clamp(y+Math.floor(r()*7)-3,1,heightCells-h-1);const room={id:`room-${i+1}`,type:'room',name:i===0?'Entry':`Area ${i+1}`,shape:'rect',x,y,w,h,properties:{}};regions.push(room);if(prev){const x1=prev.x+Math.floor(prev.w/2),y1=prev.y+Math.floor(prev.h/2),x2=x+Math.floor(w/2),y2=y+Math.floor(h/2);regions.push({id:`corridor-${i}`,type:'corridor',shape:'polyline',points:[[x1,y1],[x2,y1],[x2,y2]],width:1,properties:{}});}prev=room;}
 const walls=[];for(const room of regions.filter(q=>q.type==='room')){const {x,y,w,h}=room;walls.push({id:`${room.id}-n`,x1:x,y1:y,x2:x+w,y2:y,blocksMovement:true,blocksVision:true},{id:`${room.id}-e`,x1:x+w,y1:y,x2:x+w,y2:y+h,blocksMovement:true,blocksVision:true},{id:`${room.id}-s`,x1:x,y1:y+h,x2:x+w,y2:y+h,blocksMovement:true,blocksVision:true},{id:`${room.id}-w`,x1:x,y1:y,x2:x,y2:y+h,blocksMovement:true,blocksVision:true});}
 const doors=[];for(let i=1;i<count;i++){const a=regions.find(q=>q.id===`room-${i}`),b=regions.find(q=>q.id===`room-${i+1}`);if(a&&b)doors.push({id:`door-${i}`,x:Math.round((a.x+a.w+b.x)/2),y:Math.round(a.y+a.h/2),orientation:90,isOpen:true,isLocked:false});}
 const objects=[];if(regions[0])objects.push({id:'landmark-1',type:'marker',name:'Landmark',x:regions[0].x+2,y:regions[0].y+2});return{version:1,name,widthCells,heightCells,cellSizeFt,northAngle:0,theme:'dark-stone',regions,walls,doors,objects,effects:[]};
}
function normalizeSpec(map){const s=map?.generated_spec||{};if(Array.isArray(s.rooms)&&!s.regions){const widthCells=Number(map.width)||30,heightCells=Number(map.height)||22;return{version:1,name:map.name,widthCells,heightCells,cellSizeFt:Number(map.grid_size)||5,northAngle:Number(map.north_angle)||0,theme:s.theme||'dark-stone',regions:s.rooms.map((r,i)=>({id:`legacy-room-${i}`,type:'room',shape:'rect',x:(Number(r.x)||0)/100*widthCells,y:(Number(r.y)||0)/100*heightCells,w:(Number(r.w)||10)/100*widthCells,h:(Number(r.h)||10)/100*heightCells,properties:{}})),walls:[],doors:[],objects:[],effects:[]};}return{version:1,name:map?.name||s.name||'Map',widthCells:Number(s.widthCells||map?.width||30),heightCells:Number(s.heightCells||map?.height||22),cellSizeFt:Number(s.cellSizeFt||map?.grid_size||5),northAngle:Number(s.northAngle??map?.north_angle??0),theme:s.theme||'dark-stone',regions:Array.isArray(s.regions)?s.regions:[],walls:Array.isArray(s.walls)?s.walls:[],doors:Array.isArray(s.doors)?s.doors:[],objects:Array.isArray(s.objects)?s.objects:[],effects:Array.isArray(s.effects)?s.effects:[]};}
function mapTokenPos(t,s){let x=Number(t?.x),y=Number(t?.y);if(!Number.isFinite(x))x=s.widthCells/2;if(!Number.isFinite(y))y=s.heightCells/2;const grid=t?.state?.position_mode==='grid'||(x<=s.widthCells&&y<=s.heightCells);if(!grid){x=x/100*s.widthCells;y=y/100*s.heightCells;}return{x:clamp(x,0,s.widthCells),y:clamp(y,0,s.heightCells)};}
function palette(type){if(type==='enemy')return'#9d4c4c';if(type==='npc')return'#4e718d';return'#c49b42';}
function segIntersect(a,b,c,d){const ccw=(p1,p2,p3)=>(p3.y-p1.y)*(p2.x-p1.x)>(p2.y-p1.y)*(p3.x-p1.x);return ccw(a,c,d)!==ccw(b,c,d)&&ccw(a,b,c)!==ccw(a,b,d);}
function canMove(spec,from,to){for(const w of spec.walls||[]){if(w.blocksMovement===false)continue;if(segIntersect(from,to,{x:Number(w.x1),y:Number(w.y1)},{x:Number(w.x2),y:Number(w.y2)}))return{ok:false,reason:'A wall blocks that movement.'};}for(const d of spec.doors||[]){if(d.isOpen)continue;const a={x:Number(d.x)-.5,y:Number(d.y)},b={x:Number(d.x)+.5,y:Number(d.y)};if(segIntersect(from,to,a,b))return{ok:false,reason:d.isLocked?'That door is locked.':'That door is closed.'};}return{ok:true};}
function movementCost(spec,from,to){const dx=Math.abs(to.x-from.x),dy=Math.abs(to.y-from.y);let feet=Math.max(dx,dy)*Number(spec.cellSizeFt||5);const difficult=(spec.regions||[]).some(r=>r.properties?.difficultTerrain&&r.shape==='rect'&&to.x>=r.x&&to.x<=r.x+r.w&&to.y>=r.y&&to.y<=r.y+r.h);if(difficult)feet*=2;return Math.round(feet);}
function setupFrame(frame,mode,label,onMode){injectStyles();frame.innerHTML='';const shell=document.createElement('div');shell.className='ddMapShell';const bar=document.createElement('div');bar.className='ddMapToolbar';bar.innerHTML=`<button data-dd-map-mode="tactical" class="${mode==='tactical'?'active':''}">Tactical</button><button data-dd-map-mode="world" class="${mode==='world'?'active':''}">World</button><span class="ddMapLocation">${esc(label||'')}</span>`;bar.querySelectorAll('[data-dd-map-mode]').forEach(b=>b.onclick=()=>onMode?.(b.dataset.ddMapMode));const wrap=document.createElement('div');wrap.className='ddMapCanvasWrap';if(mode==='world')wrap.classList.add('ddWorldMapWrap');shell.append(bar,wrap);frame.appendChild(shell);return wrap;}
function compass(ctx,w,angle=0){ctx.save();ctx.translate(w-34,34);ctx.rotate(Number(angle||0)*Math.PI/180);ctx.fillStyle='rgba(8,10,13,.82)';ctx.strokeStyle='rgba(233,201,126,.8)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#f0d488';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText('N',0,-8);ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(-5,8);ctx.lineTo(0,5);ctx.lineTo(5,8);ctx.closePath();ctx.fill();ctx.restore();}
function renderTactical(frame,{map,tokens=[],userId,characterId,mapView,onMoveToken,onModeChange,compact=false}={}){const wrap=setupFrame(frame,'tactical',map?.name||'No tactical map',onModeChange);if(!map){wrap.innerHTML='<div class="ddMapEmpty"><div><strong>No tactical map yet</strong>The AI DM will create one when the party enters a mapped location. Campaign owners can also use Generate Map.</div></div>';return;}const spec=normalizeSpec(map),width=Math.max(320,Math.floor(frame.clientWidth||560)),height=Math.max(compact?230:320,Math.round(width*spec.heightCells/spec.widthCells)),canvas=document.createElement('canvas'),dpr=Math.min(2,window.devicePixelRatio||1);canvas.className='ddMapCanvas';canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);canvas.style.height=`${height}px`;wrap.appendChild(canvas);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const sx=width/spec.widthCells,sy=height/spec.heightCells;ctx.fillStyle='#0a0d11';ctx.fillRect(0,0,width,height);
 for(const r of spec.regions){if(r.type==='corridor'&&Array.isArray(r.points)){ctx.strokeStyle='#2d3133';ctx.lineWidth=Math.max(sx,sy)*(Number(r.width)||1);ctx.lineCap='square';ctx.beginPath();r.points.forEach((p,i)=>i?ctx.lineTo(p[0]*sx,p[1]*sy):ctx.moveTo(p[0]*sx,p[1]*sy));ctx.stroke();continue;}if(r.shape==='rect'||r.type==='room'||r.type==='terrain'){ctx.fillStyle=r.properties?.difficultTerrain?'#313328':r.type==='terrain'?'#263039':'#22272a';ctx.fillRect(Number(r.x)*sx,Number(r.y)*sy,Number(r.w)*sx,Number(r.h)*sy);}}
 ctx.strokeStyle='rgba(184,171,137,.12)';ctx.lineWidth=1;for(let x=0;x<=spec.widthCells;x++){ctx.beginPath();ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,height);ctx.stroke();}for(let y=0;y<=spec.heightCells;y++){ctx.beginPath();ctx.moveTo(0,y*sy);ctx.lineTo(width,y*sy);ctx.stroke();}ctx.strokeStyle='#858178';ctx.lineWidth=3;for(const w of spec.walls){ctx.beginPath();ctx.moveTo(Number(w.x1)*sx,Number(w.y1)*sy);ctx.lineTo(Number(w.x2)*sx,Number(w.y2)*sy);ctx.stroke();}for(const d of spec.doors){ctx.strokeStyle=d.isOpen?'#78a579':'#d1a357';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo((Number(d.x)-.45)*sx,Number(d.y)*sy);ctx.lineTo((Number(d.x)+.45)*sx,Number(d.y)*sy);ctx.stroke();}
 for(const e of spec.effects){const x=Number(e.x??e.geometry?.center?.[0]),y=Number(e.y??e.geometry?.center?.[1]),rf=Number((e.radiusFt??e.geometry?.radiusFt)||5),rad=rf/spec.cellSizeFt*sx;ctx.fillStyle='rgba(103,85,158,.23)';ctx.beginPath();ctx.arc(x*sx,y*sy,rad,0,Math.PI*2);ctx.fill();}for(const o of spec.objects){ctx.fillStyle='#8d8268';ctx.beginPath();ctx.arc(Number(o.x)*sx,Number(o.y)*sy,Math.max(3,sx*.18),0,Math.PI*2);ctx.fill();}
 const mapTokens=tokens.filter(t=>!t.map_id||t.map_id===map.id),own=mapTokens.find(t=>t.owner_user_id===userId)||mapTokens.find(t=>t.character_id===characterId),tokenBoxes=[];for(const t of mapTokens){const p=mapTokenPos(t,spec),rad=clamp(Math.min(sx,sy)*.34,8,16);ctx.fillStyle=palette(t.token_type);ctx.strokeStyle=t.owner_user_id===userId?'#ffe095':'#15191e';ctx.lineWidth=t.owner_user_id===userId?3:2;ctx.beginPath();ctx.arc(p.x*sx,p.y*sy,rad,0,Math.PI*2);ctx.fill();ctx.stroke();const nm=String(t.name||'?');ctx.fillStyle='#fff';ctx.font='bold 9px system-ui';ctx.textAlign='center';ctx.fillText(nm.slice(0,2).toUpperCase(),p.x*sx,p.y*sy+3);tokenBoxes.push({t,p,cx:p.x*sx,cy:p.y*sy,r:rad+7});}
 if(own){const p=mapTokenPos(own,spec),vision=Number(mapView?.view_state?.visionCells||6),gx=p.x*sx,gy=p.y*sy,vr=vision*Math.min(sx,sy);ctx.save();ctx.fillStyle='rgba(0,0,0,.52)';ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(gx,gy,vr*.35,gx,gy,vr);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(.75,'rgba(0,0,0,.94)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(gx,gy,vr,0,Math.PI*2);ctx.fill();ctx.restore();const visionBadge=document.createElement('div');visionBadge.className='ddMapVision';visionBadge.textContent='Your current vision';wrap.appendChild(visionBadge);}compass(ctx,width,spec.northAngle);const tip=document.createElement('div');tip.className='ddMapTip';tip.textContent=own?'Drag your token to move · 5 ft grid':'5 ft tactical grid';wrap.appendChild(tip);
 let drag=null;const point=e=>{const r=canvas.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*spec.widthCells,0,spec.widthCells),y:clamp((e.clientY-r.top)/r.height*spec.heightCells,0,spec.heightCells)};};canvas.addEventListener('pointerdown',e=>{const p=point(e),px=p.x*sx,py=p.y*sy,hit=tokenBoxes.find(b=>b.t.owner_user_id===userId&&Math.hypot(px-b.cx,py-b.cy)<=b.r);if(hit){drag={token:hit.t,from:hit.p};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointerup',async e=>{if(!drag)return;const to=point(e),snap={x:Math.round(to.x*2)/2,y:Math.round(to.y*2)/2},check=canMove(spec,drag.from,snap),cost=movementCost(spec,drag.from,snap),d=drag;drag=null;if(!check.ok){window.dispatchEvent(new CustomEvent('dd:map-move-rejected',{detail:{message:check.reason}}));return;}await onMoveToken?.(d.token,snap,{feet:cost,from:d.from,spec});});}
function renderWorld(frame,{worldMap,onModeChange,onSelectLocation}={}){const st=worldMap?.state||worldMap||{},locations=Array.isArray(st.locations)?st.locations:[],routes=Array.isArray(st.routes)?st.routes:[],wrap=setupFrame(frame,'world','Discovered World',onModeChange);if(!locations.length){wrap.innerHTML='<div class="ddMapEmpty"><div><strong>No discovered locations yet</strong>Locations and routes will appear here automatically as the party discovers them.</div></div>';return;}const width=Math.max(320,Math.floor(frame.clientWidth||560)),height=Math.max(320,Math.round(width*.68)),canvas=document.createElement('canvas'),dpr=Math.min(2,window.devicePixelRatio||1);canvas.className='ddMapCanvas';canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.height=`${height}px`;wrap.appendChild(canvas);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const bg=ctx.createLinearGradient(0,0,width,height);bg.addColorStop(0,'#332d20');bg.addColorStop(.55,'#28271c');bg.addColorStop(1,'#1d241d');ctx.fillStyle=bg;ctx.fillRect(0,0,width,height);ctx.strokeStyle='rgba(226,198,128,.10)';for(let i=0;i<12;i++){ctx.beginPath();ctx.moveTo(0,i*height/12);ctx.lineTo(width,i*height/12);ctx.stroke();}const pos=l=>({x:clamp(Number(l.x??50),4,96)/100*width,y:clamp(Number(l.y??50),7,93)/100*height});for(const r of routes){const a=locations.find(l=>l.id===r.from),b=locations.find(l=>l.id===r.to);if(!a||!b)continue;const p=pos(a),q=pos(b);ctx.strokeStyle=r.blocked?'#8b5c52':'#9a8965';ctx.lineWidth=2;ctx.setLineDash(r.routeType==='trail'?[5,5]:[]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.setLineDash([]);}const hits=[];for(const l of locations){const p=pos(l),current=l.id===st.currentLocationId;ctx.fillStyle=current?'#d4ad53':'#5f7d68';ctx.strokeStyle=current?'#ffe09a':'#bdc8be';ctx.lineWidth=current?3:1.5;ctx.beginPath();ctx.arc(p.x,p.y,current?9:7,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#f0e7d6';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(String(l.name||'Location').slice(0,26),p.x,p.y+20);hits.push({l,p,r:18});}compass(ctx,width,Number(st.northAngle)||0);const tip=document.createElement('div');tip.className='ddMapTip';tip.textContent='Discovered world · no fog of war · tap a location to view its local map';wrap.appendChild(tip);canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),p={x:(e.clientX-r.left)/r.width*width,y:(e.clientY-r.top)/r.height*height},hit=hits.find(h=>Math.hypot(p.x-h.p.x,p.y-h.p.y)<=h.r);if(hit)onSelectLocation?.(hit.l);});}
window.DungeonMapEngine={starterSpec,normalizeSpec,renderTactical,renderWorld,canMove,movementCost};
})();