(()=>{
'use strict';
if(window.__DD_NAV_LAYOUT_V7)return;window.__DD_NAV_LAYOUT_V7=true;
const $=(s,r=document)=>r.querySelector(s);
const PDF_WORKER_SRC='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const characterIcon='<svg viewBox="0 0 48 48"><circle cx="24" cy="15" r="7"/><path d="M11 41c1-11 6-17 13-17s12 6 13 17"/></svg>';
const npcIcon='<svg viewBox="0 0 48 48"><circle cx="24" cy="15" r="8"/><path d="M10 41c1-10 6-16 14-16s13 6 14 16M6 36c1-6 4-10 9-12m27 12c-1-6-4-10-9-12"/></svg>';
function patchPdfLib(lib){
  if(!lib)return;
  if(lib.GlobalWorkerOptions&&!lib.GlobalWorkerOptions.workerSrc)lib.GlobalWorkerOptions.workerSrc=PDF_WORKER_SRC;
  if(lib.__ddPositionExtraction)return;const original=lib.getDocument?.bind(lib);if(!original)return;lib.__ddPositionExtraction=true;
  lib.getDocument=(...args)=>{if(lib.GlobalWorkerOptions&&!lib.GlobalWorkerOptions.workerSrc)lib.GlobalWorkerOptions.workerSrc=PDF_WORKER_SRC;const task=original(...args);task?.promise?.then(pdf=>{if(!pdf||pdf.__ddPositionExtraction)return;pdf.__ddPositionExtraction=true;const getPage=pdf.getPage.bind(pdf);pdf.getPage=async pageNumber=>{const page=await getPage(pageNumber);if(!page||page.__ddPositionExtraction)return page;page.__ddPositionExtraction=true;const getTextContent=page.getTextContent.bind(page);page.getTextContent=async options=>{const content=await getTextContent(options),extras=[];let serial=0;const h=Math.abs(Number(page.view?.[3]||792)-Number(page.view?.[1]||0))||792;for(const item of content.items||[]){if(!item?.str)continue;const x=Number(item.transform?.[4]||0),y=Number(item.transform?.[5]||0),payload=JSON.stringify({p:pageNumber,h:Math.round(h*10)/10,x:Math.round(x*10)/10,y:Math.round(y*10)/10,s:String(item.str)});extras.push({str:`[PDF ITEM] ${payload}`,dir:'ltr',width:0,height:0,transform:[1,0,0,1,0,-10000-(serial++)],fontName:''});}let annotations=[];try{annotations=await page.getAnnotations({intent:'display'});}catch{}for(const a of annotations||[]){if(a?.subtype!=='Widget'||!a?.fieldName)continue;let value=a.fieldValue;if(Array.isArray(value))value=value.join(', ');if(value===undefined||value===null||value==='')continue;const v=String(value).replace(/\s+/g,' ').trim();extras.push({str:`[FORM FIELD] ${String(a.fieldName).trim()}: ${v}`,dir:'ltr',width:0,height:0,transform:[1,0,0,1,0,-10000-(serial++)],fontName:''});}return extras.length?{...content,items:[...(content.items||[]),...extras]}:content;};return page;};}).catch(()=>{});return task;};
}
function installPdfPatch(){if(window.pdfjsLib){patchPdfLib(window.pdfjsLib);return;}let pending;try{Object.defineProperty(window,'pdfjsLib',{configurable:true,get(){return pending},set(v){pending=v;patchPdfLib(v)}})}catch{}}
function apply(){const bottomNpc=$('.bottomNav [data-page="npc"]');if(bottomNpc&&!bottomNpc.dataset.ddSwapped){bottomNpc.dataset.page='character';bottomNpc.dataset.ddSwapped='1';bottomNpc.innerHTML=`${characterIcon}<span>Character</span>`;bottomNpc.setAttribute('aria-label','Character sheet');}const quickCharacter=$('.quickGrid .quick[data-page="character"]');if(quickCharacter&&!quickCharacter.dataset.ddSwapped){quickCharacter.dataset.page='npc';quickCharacter.dataset.ddSwapped='1';quickCharacter.innerHTML=`${npcIcon}<span>NPCs</span>`;quickCharacter.setAttribute('aria-label','NPCs');}const pdfLabel=document.querySelector('label[for="characterPdf"]');if(pdfLabel&&pdfLabel.textContent!=='Import PDF')pdfLabel.textContent='Import PDF';}
installPdfPatch();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();