(()=>{
'use strict';
if(window.DungeonRulesV2)return;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const norm=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const clone=v=>JSON.parse(JSON.stringify(v??{}));
const arr=v=>Array.isArray(v)?v:[];
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const ABILITIES=['strength','dexterity','constitution','intelligence','wisdom','charisma'];
const ABILITY_ALIAS={str:'strength',dex:'dexterity',con:'constitution',int:'intelligence',wis:'wisdom',cha:'charisma'};
const SIZE_CELLS={tiny:.5,small:1,medium:1,large:2,huge:3,gargantuan:4};
const XP_LEVELS=[0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
const CONDITIONS={
 blinded:{attackDisadvantage:true,attackersAdvantage:true},
 charmed:{},
 deafened:{},
 frightened:{attackDisadvantage:true},
 grappled:{speedZero:true},
 incapacitated:{noActions:true,noReactions:true},
 invisible:{attackAdvantage:true,attackersDisadvantage:true},
 paralyzed:{noActions:true,noReactions:true,speedZero:true,attackersAdvantage:true},
 petrified:{noActions:true,noReactions:true,speedZero:true,attackersAdvantage:true},
 poisoned:{attackDisadvantage:true,checkDisadvantage:true},
 prone:{attackDisadvantage:true},
 restrained:{speedZero:true,attackDisadvantage:true,attackersAdvantage:true,dexSaveDisadvantage:true},
 stunned:{noActions:true,noReactions:true,speedZero:true,attackersAdvantage:true},
 unconscious:{noActions:true,noReactions:true,speedZero:true,attackersAdvantage:true}
};
function profileOf(c){return c?.profile||c||{};}
function defenses(c){const p=profileOf(c);return p.defenses||(p.defenses={});}
function abilityEntry(c,key){const p=profileOf(c),k=ABILITY_ALIAS[norm(key)]||norm(key);return p.abilities?.[k]||p.abilities?.[k.slice(0,3)]||{};}
function abilityMod(c,key){const e=abilityEntry(c,key);if(Number.isFinite(Number(e.mod)))return Number(e.mod);if(Number.isFinite(Number(e.modifier)))return Number(e.modifier);const score=n(e.score,10);return Math.floor((score-10)/2);}
function proficiency(c){const p=profileOf(c);return n(first(p.proficiencyBonus,p.proficiency,p.identity?.proficiencyBonus),2);}
function conditions(c){return arr(defenses(c).conditions).map(x=>typeof x==='string'?{name:x}:{...x,name:x?.name||x?.condition||''}).filter(x=>x.name);}
function conditionFlags(c){const out={};for(const q of conditions(c)){const f=CONDITIONS[norm(q.name)]||{};for(const [k,v] of Object.entries(f))if(v)out[k]=true;}return out;}
function hasCondition(c,name){const k=norm(name);return conditions(c).some(x=>norm(x.name)===k);}
function hp(c){const d=defenses(c);return n(first(c?.hp,d.currentHp,d.hp),0);}
function maxHp(c){const d=defenses(c);return Math.max(0,n(first(c?.max_hp,d.maxHp,d.maxHP),hp(c)));}
function tempHp(c){const d=defenses(c);return Math.max(0,n(first(d.tempHp,d.temporaryHp),0));}
function ac(c){return n(first(c?.ac,defenses(c).armorClass,defenses(c).ac),10);}
function speed(c){const p=profileOf(c),d=defenses(c),raw=first(p.movement?.walk,p.speed,p.identity?.speed,d.speed,30);if(typeof raw==='string'){const m=raw.match(/\d+/);return m?Number(m[0]):30;}return n(raw,30);}
function size(c){const p=profileOf(c);return norm(first(p.identity?.size,p.size,'medium'))||'medium';}
function sizeCells(c){return SIZE_CELLS[size(c)]||1;}
function level(c){const p=profileOf(c);return Math.max(1,n(first(p.identity?.level,p.level),1));}
function xp(c){const p=profileOf(c);return Math.max(0,n(first(p.identity?.xp,p.xp,p.experience),0));}
function levelFromXp(v){let lv=1;for(let i=0;i<XP_LEVELS.length;i++)if(v>=XP_LEVELS[i])lv=i+1;return lv;}
function nextLevelXp(c){const lv=level(c);return lv>=20?null:XP_LEVELS[lv];}
function resourceMap(c){const p=profileOf(c);return p.resources||(p.resources={});}
function resourceValue(c,key){const r=resourceMap(c)?.[key];if(r&&typeof r==='object')return n(first(r.current,r.value,r.remaining),0);return n(r,0);}
function resourceMax(c,key){const r=resourceMap(c)?.[key];return r&&typeof r==='object'?n(first(r.max,r.maximum,r.total),resourceValue(c,key)):resourceValue(c,key);}
function equippedItems(c){const p=profileOf(c),eq=p.equipment||{};return [...arr(eq.weapons),...arr(eq.armor),...arr(eq.gear),...arr(eq.consumables),...arr(eq.magicItems),...arr(p.magicItems)];}
function parseDice(text){const m=String(text||'').replace(/\s+/g,'').match(/(\d+)d(\d+)([+-]\d+)?/i);return m?{count:n(m[1],1),sides:n(m[2],20),mod:n(m[3],0),expression:m[0]}:null;}
function parseRange(raw){if(Number.isFinite(Number(raw)))return{normal:Number(raw),long:null,unit:'ft'};const s=String(raw||'').toLowerCase();if(s.includes('self'))return{normal:0,long:0,self:true,unit:'ft'};if(s.includes('touch'))return{normal:5,long:5,touch:true,unit:'ft'};const slash=s.match(/(\d+)\s*\/\s*(\d+)/);if(slash)return{normal:Number(slash[1]),long:Number(slash[2]),unit:'ft'};const m=s.match(/(\d+)\s*(?:ft|feet|foot)/);return{normal:m?Number(m[1]):5,long:null,unit:'ft'};}
function actionId(prefix,name,i=0){return`${prefix}:${norm(name)||i}`;}
function normalizeWeapon(w,i=0){const name=w?.name||`Weapon ${i+1}`,damage=first(w.damage,w.damageDice,w.rulesProfile?.damage),attackBonus=first(w.attackBonus,w.attack_bonus,w.toHit,w.rulesProfile?.attackBonus),range=parseRange(first(w.range,w.rulesProfile?.range,w.properties));return{id:actionId('weapon',name,i),kind:'weapon',name,activation:'action',attackType:String(first(w.attackType,w.type,'weapon')).toLowerCase(),attackBonus:Number.isFinite(Number(attackBonus))?Number(attackBonus):null,damage:String(damage||''),damageType:first(w.damageType,w.rulesProfile?.damageType),range,properties:String(first(w.properties,w.rulesProfile?.properties,'')),resource:w.ammunition?{key:norm(w.ammunition),cost:1}:null,source:w};}
function normalizeAttack(a,i=0){const name=a?.name||`Attack ${i+1}`,range=parseRange(first(a.range,a.reach));return{id:a.id||actionId('attack',name,i),kind:a.kind||'attack',name,activation:first(a.activation,a.actionType,'action'),attackBonus:Number.isFinite(Number(first(a.attackBonus,a.toHit)))?Number(first(a.attackBonus,a.toHit)):null,saveAbility:first(a.saveAbility,a.save),saveDC:Number.isFinite(Number(first(a.saveDC,a.dc)))?Number(first(a.saveDC,a.dc)):null,damage:String(first(a.damage,a.damageDice,'')),damageType:a.damageType,healing:String(first(a.healing,a.heal,'')),range,resource:a.resource||null,target:a.target||'creature',source:a};}
function normalizeSpell(s,i=0){const name=s?.name||`Spell ${i+1}`,range=parseRange(s.range),level=n(s.level,0),activation=String(first(s.activation,s.castingTime,'action')).toLowerCase();return{id:s.id||actionId('spell',name,i),kind:'spell',name,activation,level,range,attackBonus:Number.isFinite(Number(first(s.attackBonus,s.spellAttackBonus)))?Number(first(s.attackBonus,s.spellAttackBonus)):null,saveAbility:first(s.saveAbility,s.save),saveDC:Number.isFinite(Number(first(s.saveDC,s.dc)))?Number(first(s.saveDC,s.dc)):null,damage:String(first(s.damage,s.damageDice,'')),damageType:s.damageType,healing:String(first(s.healing,s.heal,'')),concentration:!!s.concentration,duration:s.duration||null,area:s.area||null,target:s.target||'creature',resource:level>0?{spellSlotLevel:level,cost:1}:null,source:s};}
function normalizeFeature(f,i=0){const name=f?.name||`Feature ${i+1}`,activation=String(first(f.activation,f.actionType,f.useType,'passive')).toLowerCase();return{id:f.id||actionId('feature',name,i),kind:'feature',name,activation,range:parseRange(f.range),attackBonus:Number.isFinite(Number(f.attackBonus))?Number(f.attackBonus):null,saveAbility:first(f.saveAbility,f.save),saveDC:Number.isFinite(Number(first(f.saveDC,f.dc)))?Number(first(f.saveDC,f.dc)):null,damage:String(first(f.damage,f.damageDice,'')),healing:String(first(f.healing,f.heal,'')),resource:f.resource||((f.uses||f.maxUses)?{key:norm(name),cost:1}:null),target:f.target||null,source:f};}
function normalizeItem(it,i=0){const name=it?.name||`Item ${i+1}`,usable=it?.usable!==false&&(it?.effect||it?.healing||it?.damage||it?.consumable||it?.category==='consumable'||it?.charges);return{id:it.id||actionId('item',name,i),kind:'item',name,activation:String(first(it.activation,it.actionType,'action')).toLowerCase(),range:parseRange(it.range),damage:String(first(it.damage,'')),healing:String(first(it.healing,it.heal,'')),target:it.target||null,quantity:n(first(it.quantity,it.qty),1),charges:n(it.charges,0),usable,source:it};}
function spellList(p){const sc=p.spellcasting||{};return arr(first(sc.spells,p.spells,[]));}
function actionCatalog(c,{includePassive=false}={}){const p=profileOf(c),eq=p.equipment||{},out=[];arr(eq.weapons).forEach((w,i)=>out.push(normalizeWeapon(w,i)));arr(p.attacks).forEach((a,i)=>out.push(normalizeAttack(a,i)));spellList(p).forEach((s,i)=>out.push(normalizeSpell(s,i)));[...arr(p.classFeatures),...arr(p.speciesFeatures),...arr(p.backgroundFeatures),...arr(p.feats),...arr(p.features)].forEach((f,i)=>{const a=normalizeFeature(f,i);if(includePassive||a.activation!=='passive')out.push(a);});[...arr(eq.consumables),...arr(eq.magicItems),...arr(p.magicItems),...arr(eq.gear).filter(x=>x?.usable||x?.effect||x?.charges)].forEach((it,i)=>{const a=normalizeItem(it,i);if(a.usable)out.push(a);});out.push({id:'basic:dash',kind:'basic',name:'Dash',activation:'action',source:{}},{id:'basic:disengage',kind:'basic',name:'Disengage',activation:'action',source:{}},{id:'basic:dodge',kind:'basic',name:'Dodge',activation:'action',source:{}},{id:'basic:help',kind:'basic',name:'Help',activation:'action',target:'creature',range:{normal:5,long:5},source:{}},{id:'basic:hide',kind:'basic',name:'Hide',activation:'action',source:{}},{id:'basic:ready',kind:'basic',name:'Ready',activation:'action',source:{}},{id:'basic:search',kind:'basic',name:'Search',activation:'action',source:{}},{id:'basic:study',kind:'basic',name:'Study',activation:'action',source:{}},{id:'basic:influence',kind:'basic',name:'Influence',activation:'action',source:{}},{id:'basic:grapple',kind:'basic',name:'Grapple',activation:'attack',target:'creature',range:{normal:5,long:5},source:{}},{id:'basic:shove',kind:'basic',name:'Shove',activation:'attack',target:'creature',range:{normal:5,long:5},source:{}});const seen=new Set();return out.filter(a=>{const k=a.id||`${a.kind}:${norm(a.name)}`;if(seen.has(k))return false;seen.add(k);return true;});}
function spellSlots(p){return p.spellcasting?.slots||{};}
function slotAvailable(c,level){if(!level)return true;const slots=spellSlots(profileOf(c)),r=slots[level]??slots[String(level)]??slots[`level${level}`];if(r&&typeof r==='object')return n(first(r.current,r.remaining,r.value),0)>0;return n(r,0)>0;}
function resourceAvailable(c,res){if(!res)return true;if(res.spellSlotLevel)return slotAvailable(c,res.spellSlotLevel);if(res.key)return resourceValue(c,res.key)>=n(res.cost,1);return true;}
function distanceFt(a,b,cellSize=5){if(!a||!b)return Infinity;const dx=Math.abs(n(a.x)-n(b.x)),dy=Math.abs(n(a.y)-n(b.y));return Math.max(dx,dy)*n(cellSize,5);}
function lineIntersects(a,b,c,d){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);const c1=cross(a,b,c),c2=cross(a,b,d),c3=cross(c,d,a),c4=cross(c,d,b);return ((c1===0&&c2===0)||(c1*c2<=0&&c3*c4<=0));}
function lineOfSight(spec,a,b){if(!spec||!a||!b)return{clear:true,cover:0};let cover=0;for(const w of arr(spec.walls)){if(w.blocksVision===false)continue;if(lineIntersects(a,b,{x:n(w.x1),y:n(w.y1)},{x:n(w.x2),y:n(w.y2)}))return{clear:false,cover:3,reason:'A wall blocks line of sight.'};}for(const d of arr(spec.doors)){if(d.isOpen)continue;const horizontal=Number(d.orientation||0)%180===0,c={x:n(d.x)+(horizontal?-.5:0),y:n(d.y)+(horizontal?0:-.5)},e={x:n(d.x)+(horizontal?.5:0),y:n(d.y)+(horizontal?0:.5)};if(lineIntersects(a,b,c,e))return{clear:false,cover:3,reason:'A closed door blocks line of sight.'};}for(const o of arr(spec.objects)){if(!o?.blocksVision&&!o?.cover)continue;const ox=n(o.x),oy=n(o.y),r=Math.max(.25,n(first(o.radius,o.width),.5));const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;if(Math.hypot(mx-ox,my-oy)<=r)cover=Math.max(cover,n(o.cover,2));}return{clear:true,cover};}
function inferAdvantage(actor,target,kind='attack'){const af=conditionFlags(actor),tf=conditionFlags(target),reasons=[];let score=0;if(kind==='attack'){if(af.attackAdvantage){score++;reasons.push('actor advantage condition');}if(af.attackDisadvantage){score--;reasons.push('actor disadvantage condition');}if(tf.attackersAdvantage){score++;reasons.push('target grants advantage');}if(tf.attackersDisadvantage){score--;reasons.push('target imposes disadvantage');}}return{mode:score>0?'advantage':score<0?'disadvantage':'normal',reasons};}
function actionLegality(action,actor,{target,distance,los,inCombat=true,turn=true,reaction=false}={}){const flags=conditionFlags(actor),reasons=[];if(flags.noActions&&!reaction)reasons.push('You cannot take actions right now.');if(flags.noReactions&&reaction)reasons.push('You cannot take reactions right now.');if(!resourceAvailable(actor,action.resource))reasons.push('Required resource is unavailable.');if(action.kind==='spell'&&action.level>0&&!slotAvailable(actor,action.level))reasons.push(`No level ${action.level} spell slot is available.`);if(target&&Number.isFinite(distance)){const rg=action.range||{normal:5};if(rg.self&&target!==actor)reasons.push('This action targets self.');else if(rg.long&&distance>rg.long)reasons.push('Target is out of range.');else if(!rg.long&&Number.isFinite(rg.normal)&&distance>rg.normal)reasons.push('Target is out of range.');}if(target&&los?.clear===false&&!action.source?.ignoresLineOfSight)reasons.push(los.reason||'Line of sight is blocked.');if(inCombat&&!turn&&action.activation!=='reaction'&&!reaction)reasons.push('It is not your active block.');return{ok:reasons.length===0,reasons};}
function attackModifier(actor,action){if(Number.isFinite(Number(action.attackBonus)))return Number(action.attackBonus);const p=profileOf(actor),finesse=/finesse/i.test(action.properties||''),ranged=/ranged|bow|crossbow/i.test(`${action.attackType||''} ${action.name||''} ${action.properties||''}`),ability=ranged||finesse?'dexterity':'strength';return abilityMod(actor,ability)+proficiency(actor);}
function saveDC(actor,action){if(Number.isFinite(Number(action.saveDC)))return Number(action.saveDC);const p=profileOf(actor),sc=p.spellcasting||{},abil=first(sc.ability,sc.spellcastingAbility,action.source?.ability,'wisdom');return 8+proficiency(actor)+abilityMod(actor,abil);}
function rollPlan(action,actor,{target,distance,los,cover=0}={}){const base={actionId:action.id,label:action.name,kind:action.kind,targetId:target?.id||null};if(action.id==='basic:grapple'||action.id==='basic:shove')return{...base,stage:'save',roller:'target',saveAbility:'strength-or-dexterity',dc:8+proficiency(actor)+abilityMod(actor,'strength'),hiddenDC:false};if(action.attackBonus!==null&&action.attackBonus!==undefined||action.kind==='weapon'||action.kind==='attack'){const mod=attackModifier(actor,action),adv=inferAdvantage(actor,target,'attack');return{...base,stage:'attack',roller:'actor',expression:`1d20${mod>=0?'+':''}${mod}`,mode:adv.mode,ac:target?ac(target)+n(cover,los?.cover===2?5:los?.cover===1?2:0):null,hiddenDC:false,damage:action.damage,damageType:action.damageType};}if(action.saveAbility){return{...base,stage:'save',roller:'target',saveAbility:norm(action.saveAbility),dc:saveDC(actor,action),hiddenDC:false,damage:action.damage,damageType:action.damageType};}if(action.healing){const d=parseDice(action.healing);return{...base,stage:'effect',roller:'actor',expression:d?.expression||String(action.healing),mode:'normal',effect:'healing'};}if(action.damage){const d=parseDice(action.damage);return{...base,stage:'effect',roller:'actor',expression:d?.expression||String(action.damage),mode:'normal',effect:'damage'};}return{...base,stage:'resolve',roller:'none'};}
function spendResource(profile,res){if(!res)return profile;const p=profile;if(res.spellSlotLevel){const slots=p.spellcasting=p.spellcasting||{},map=slots.slots=slots.slots||{},key=Object.keys(map).find(k=>norm(k)===norm(String(res.spellSlotLevel))||norm(k)===`level${res.spellSlotLevel}`)||String(res.spellSlotLevel),cur=map[key];if(cur&&typeof cur==='object')cur.current=Math.max(0,n(first(cur.current,cur.remaining,cur.value),0)-n(res.cost,1));else map[key]=Math.max(0,n(cur,0)-n(res.cost,1));return p;}if(res.key){const map=p.resources=p.resources||{},cur=map[res.key];if(cur&&typeof cur==='object')cur.current=Math.max(0,n(first(cur.current,cur.remaining,cur.value),0)-n(res.cost,1));else map[res.key]=Math.max(0,n(cur,0)-n(res.cost,1));}return p;}
function applyDamage(c,amount,{critical=false}={}){const out=clone(c),p=out.profile=clone(profileOf(c)),d=p.defenses=p.defenses||{},max=maxHp(out),before=hp(out),temp=tempHp(out),raw=Math.max(0,Math.floor(n(amount))),absorbed=Math.min(temp,raw),remaining=raw-absorbed,next=clamp(before-remaining,0,max);d.tempHp=temp-absorbed;d.temporaryHp=d.tempHp;d.currentHp=next;d.maxHp=max;out.hp=next;out.max_hp=max;if(before>0&&next===0){d.unconscious=true;if(remaining>=max)d.dead=true;}if(before===0&&raw>0){const deaths=d.deathSaves=d.deathSaves||{successes:0,failures:0};deaths.failures=clamp(n(deaths.failures)+ (critical?2:1),0,3);if(deaths.failures>=3)d.dead=true;}return{character:out,amount:raw,absorbed,hpBefore:before,hpAfter:next};}
function applyHealing(c,amount){const out=clone(c),p=out.profile=clone(profileOf(c)),d=p.defenses=p.defenses||{},max=maxHp(out),before=hp(out),next=clamp(before+Math.max(0,Math.floor(n(amount))),0,max);out.hp=next;out.max_hp=max;d.currentHp=next;d.maxHp=max;if(next>0){d.unconscious=false;d.deathSaves={successes:0,failures:0};}return{character:out,hpBefore:before,hpAfter:next,amount:next-before};}
function setCondition(c,name,{remove=false,source=null,duration=null}={}){const out=clone(c),p=out.profile=clone(profileOf(c)),d=p.defenses=p.defenses||{},list=conditions(out).filter(q=>norm(q.name)!==norm(name));if(!remove)list.push({name:String(name),source,duration});d.conditions=list;return out;}
function concentrationCheckDC(damage){return Math.max(10,Math.floor(n(damage)/2));}
function beginConcentration(c,spell){const out=clone(c),p=out.profile=clone(profileOf(c));p.concentration={active:true,spell:String(spell?.name||spell||'Effect'),startedAt:new Date().toISOString(),sourceId:spell?.id||null};return out;}
function endConcentration(c){const out=clone(c),p=out.profile=clone(profileOf(c));p.concentration={active:false};return out;}
function longRest(c){const out=clone(c),p=out.profile=clone(profileOf(c)),d=p.defenses=p.defenses||{},max=maxHp(out);out.hp=max;out.max_hp=max;d.currentHp=max;d.maxHp=max;d.tempHp=0;d.temporaryHp=0;d.deathSaves={successes:0,failures:0};d.exhaustion=Math.max(0,n(d.exhaustion)-1);p.concentration={active:false};const slots=p.spellcasting?.slots||{};for(const k of Object.keys(slots)){const s=slots[k];if(s&&typeof s==='object'&&Number.isFinite(Number(first(s.max,s.maximum,s.total))))s.current=Number(first(s.max,s.maximum,s.total));}for(const [k,r] of Object.entries(p.resources||{})){if(r&&typeof r==='object'&&String(r.recovery||r.reset||'').toLowerCase().includes('long')&&Number.isFinite(Number(first(r.max,r.maximum,r.total))))r.current=Number(first(r.max,r.maximum,r.total));}return out;}
function shortRest(c,{hitDiceSpent=0,healing=0}={}){let out=clone(c),p=out.profile=clone(profileOf(c));if(healing>0)out=applyHealing(out,healing).character;const hd=p.hitDice||p.resources?.hitDice;if(hd&&typeof hd==='object'&&hitDiceSpent>0)hd.current=Math.max(0,n(first(hd.current,hd.remaining),0)-hitDiceSpent);for(const [k,r] of Object.entries(p.resources||{})){if(r&&typeof r==='object'&&String(r.recovery||r.reset||'').toLowerCase().includes('short')&&Number.isFinite(Number(first(r.max,r.maximum,r.total))))r.current=Number(first(r.max,r.maximum,r.total));}out.profile=p;return out;}
function deathSave(c,total){const out=clone(c),p=out.profile=clone(profileOf(c)),d=p.defenses=p.defenses||{},ds=d.deathSaves=d.deathSaves||{successes:0,failures:0};if(total===20){return applyHealing(out,1).character;}if(total===1)ds.failures=clamp(n(ds.failures)+2,0,3);else if(total>=10)ds.successes=clamp(n(ds.successes)+1,0,3);else ds.failures=clamp(n(ds.failures)+1,0,3);if(ds.failures>=3)d.dead=true;if(ds.successes>=3)d.stable=true;return out;}
function inventoryUse(c,itemId,{charges=1,quantity=1}={}){const out=clone(c),p=out.profile=clone(profileOf(c)),eq=p.equipment||{},groups=['consumables','magicItems','gear'];for(const g of groups){const list=arr(eq[g]);const idx=list.findIndex((x,i)=>(x.id||actionId('item',x.name,i))===itemId||norm(x.name)===norm(itemId));if(idx<0)continue;const it=list[idx];if(Number.isFinite(Number(it.charges))){it.charges=Math.max(0,n(it.charges)-charges);return{character:out,item:it};}const q=n(first(it.quantity,it.qty),1)-quantity;if(q<=0)list.splice(idx,1);else it.quantity=q;eq[g]=list;return{character:out,item:it};}return{character:out,item:null};}
function levelStatus(c){const lv=level(c),byXp=levelFromXp(xp(c)),next=nextLevelXp(c);return{level:lv,xp:xp(c),eligible:byXp>lv,recommendedLevel:byXp,nextXp:next,remaining:next==null?0:Math.max(0,next-xp(c))};}
function reactionOptions(c,{enemyLeavesReach=false,trigger=null}={}){const flags=conditionFlags(c);if(flags.noReactions)return[];const out=actionCatalog(c).filter(a=>String(a.activation).includes('reaction'));if(enemyLeavesReach)out.unshift({id:'reaction:opportunity-attack',kind:'reaction',name:'Opportunity Attack',activation:'reaction',target:'triggering-creature',source:{trigger:'leaves-reach'}});return out.filter(a=>!a.resource||resourceAvailable(c,a.resource));}
function validTargets(action,actor,tokens,{spec,actorToken,charactersById=new Map()}={}){return arr(tokens).filter(t=>t.id!==actorToken?.id).map(t=>{const target=charactersById.get(t.character_id)||{id:t.character_id||t.id,profile:t.state?.profile||{},hp:t.state?.hp,max_hp:t.state?.maxHp,ac:t.state?.ac};const a={x:n(actorToken?.x),y:n(actorToken?.y)},b={x:n(t.x),y:n(t.y)},distance=distanceFt(a,b,n(spec?.cellSizeFt,5)),los=lineOfSight(spec,a,b),legal=actionLegality(action,actor,{target,distance,los});return{token:t,target,distance,los,legal};}).filter(x=>x.legal.ok);}
function summarize(c){const p=profileOf(c),d=defenses(c);return{id:c?.id||null,name:c?.display_name||c?.name||p.identity?.name||'Character',level:level(c),hp:hp(c),maxHp:maxHp(c),tempHp:tempHp(c),ac:ac(c),speed:speed(c),size:size(c),conditions:conditions(c),concentration:p.concentration||null,exhaustion:n(d.exhaustion,0),resources:clone(p.resources||{}),spellSlots:clone(p.spellcasting?.slots||{})};}
window.DungeonRulesV2={ABILITIES,CONDITIONS,profileOf,abilityMod,proficiency,conditions,conditionFlags,hasCondition,hp,maxHp,tempHp,ac,speed,size,sizeCells,level,xp,levelStatus,actionCatalog,actionLegality,rollPlan,parseDice,parseRange,resourceAvailable,spendResource,distanceFt,lineOfSight,inferAdvantage,validTargets,applyDamage,applyHealing,setCondition,concentrationCheckDC,beginConcentration,endConcentration,longRest,shortRest,deathSave,inventoryUse,reactionOptions,summarize,normalizeWeapon,normalizeSpell};
})();